"use client";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
import { downloadCsv } from "@/lib/download-csv";

type History = { id:number; title:string; language:string|null; matched_count:number; success_count:number; failure_count:number; clicked_count:number; created_at:string };
const initial = { title:"", body:"", url:"/", image:"", tag:"", language:"", certificationId:"", premiumOnly:false, userIds:"" };

export default function AdminPushClient() {
  const { token } = useAuth();
  const [form, setForm] = useState(initial); const [count,setCount]=useState<number|null>(null); const [history,setHistory]=useState<History[]>([]);
  const [loading,setLoading]=useState(false); const [result,setResult]=useState(""); const [confirming,setConfirming]=useState(false);
  const headers = { "Content-Type":"application/json", Authorization:`Bearer ${token}` };
  const target = { language: form.language || null, certificationId: form.certificationId ? Number(form.certificationId) : null, premiumOnly: form.premiumOnly, userIds: form.userIds.split(",").map(Number).filter(Boolean) };
  const loadHistory=useCallback(async()=>{ if(!token)return; const r=await fetch("/api/backend/admin/push/history",{headers:{Authorization:`Bearer ${token}`}}); if(r.ok)setHistory((await r.json()).items); },[token]);
  useEffect(()=>{loadHistory();},[loadHistory]);
  async function estimate(){const r=await fetch("/api/backend/admin/push/audience-count",{method:"POST",headers,body:JSON.stringify({target})}); const j=await r.json(); if(!r.ok)throw new Error(j.error); setCount(j.count); setConfirming(true);}
  async function send(){setLoading(true);setResult("");try{const r=await fetch("/api/backend/admin/push/send",{method:"POST",headers,body:JSON.stringify({...form,image:form.image||null,tag:form.tag||null,target})});const j=await r.json();if(!r.ok)throw new Error(j.error);setResult(`Invio completato: ${j.sent} riusciti, ${j.failed} falliti, ${j.deactivated} disattivati.`);setConfirming(false);await loadHistory();}catch(e){setResult(`Errore: ${e instanceof Error?e.message:"invio fallito"}`);}finally{setLoading(false);}}
  const field=(key:keyof typeof initial,label:string,max?:number)=><label className="grid gap-1 text-sm font-semibold">{label}{typeof form[key]==="string"&&max&&<span className="text-xs text-slate-500">{String(form[key]).length}/{max}</span>}<input value={String(form[key])} maxLength={max} onChange={e=>setForm({...form,[key]:e.target.value})} className="rounded-lg border p-2" /></label>;
  return <div className="p-6 text-slate-900"><h2 className="text-2xl font-black">Notifiche push</h2><div className="mt-5 grid gap-6 lg:grid-cols-2"><form onSubmit={e=>{e.preventDefault();estimate().catch(e=>setResult(`Errore: ${e.message}`));}} className="grid gap-3">
    {field("title","Titolo",120)}<label className="grid gap-1 text-sm font-semibold">Messaggio <span className="text-xs text-slate-500">{form.body.length}/500</span><textarea required value={form.body} maxLength={500} onChange={e=>setForm({...form,body:e.target.value})} className="rounded-lg border p-2" rows={4}/></label>{field("url","URL interno",2048)}{field("image","Immagine interna (facoltativa)",2048)}{field("tag","Tag",100)}
    <div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm font-semibold">Lingua<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})} className="rounded-lg border p-2"><option value="">Tutte</option>{["it","en","fr","es"].map(x=><option key={x}>{x}</option>)}</select></label>{field("certificationId","ID certificazione")}</div>
    {field("userIds","ID utenti separati da virgola")}<label className="flex gap-2 text-sm font-semibold"><input type="checkbox" checked={form.premiumOnly} onChange={e=>setForm({...form,premiumOnly:e.target.checked})}/>Solo Premium</label><button disabled={loading||!form.title||!form.body} className="rounded-xl bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-50">Verifica destinatari</button>
  </form><aside><h3 className="font-bold">Anteprima</h3><div className="mt-2 rounded-2xl border bg-white p-4 shadow"><strong>{form.title||"Titolo notifica"}</strong><p className="text-sm text-slate-600">{form.body||"Il messaggio apparirà qui."}</p><small>{form.url}</small></div>{confirming&&<div role="dialog" className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4"><strong>Conferma invio non annullabile</strong><p className="text-sm">Segmento: {form.language||"tutte le lingue"}{form.premiumOnly?", Premium":""}. Destinatari stimati: {count}. Titolo: {form.title}. URL: {form.url}</p><div className="flex gap-2"><button onClick={send} disabled={loading} className="rounded-lg bg-red-700 px-3 py-2 font-bold text-white">{loading?"Invio…":"Invia ora"}</button><button onClick={()=>setConfirming(false)} className="rounded-lg border px-3 py-2">Annulla</button></div></div>}{result&&<p className="mt-3 text-sm font-semibold">{result}</p>}</aside></div>
  <button onClick={()=>downloadCsv("certifyquiz-push-history.csv",history.map(h=>({...h})))} className="mt-8 rounded-xl border border-green-200 bg-green-50 px-4 py-2 font-bold text-green-800">Scarica tutti gli invii CSV</button><details className="mt-3 overflow-hidden rounded-xl border"><summary className="cursor-pointer bg-slate-50 p-4 text-lg font-bold">Ultimi invii <span className="ml-2 text-sm text-slate-500">{history.length}</span></summary><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Titolo</th><th>Lingua</th><th>Dest.</th><th>OK</th><th>Errori</th><th>Click</th><th>Data</th></tr></thead><tbody>{history.map(h=><tr key={h.id} className="border-t"><td className="py-2">{h.title}</td><td>{h.language||"tutte"}</td><td>{h.matched_count}</td><td>{h.success_count}</td><td>{h.failure_count}</td><td>{h.clicked_count}</td><td>{new Date(h.created_at).toLocaleString("it-IT")}</td></tr>)}</tbody></table></div></details></div>;
}
