"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { apiFetch } from "@/lib/auth";
import { useAuth } from "@/components/auth/AuthProvider";
import type { CertificationResources } from "@/lib/data";
import { pricingPath, type Locale } from "@/lib/paths";

type Offer = { code:string; productCode:string; name:string; amountMinor:number; effectiveAmountMinor:number|null; creditMinor:number; purchaseType:string|null; blockedReason:string|null; currency:string; status:string; checkoutAvailable:boolean };
type Payload = { offers:Offer[]; owned:{tier:string}|null; premium:boolean; darkLaunch:boolean };

const TEXT = {
  it:{title:"Scegli come prepararti",free:"Free",freeBody:"Inizia gratuitamente con quiz, ripassi e anteprime.",dolphin:"Preparazione teorica completa",octopus:"Teoria e pratica interattiva",premium:"Tutta CertifyQuiz per chi prepara più certificazioni.",one:"pagamento unico",buy:"Scegli",upgrade:"Passa a Octopus",owned:"Già acquistato",inactive:"Dark launch — solo anteprima admin",warning:"Questo contenuto è già incluso nel tuo Premium. Acquista il pacchetto solo se desideri mantenere l'accesso a questa certificazione anche dopo la fine dell'abbonamento.",buyAnyway:"Acquista comunque",noExpiry:"Accesso senza scadenza ai contenuti inclusi, finché CertifyQuiz rimane disponibile.",quiz:"quiz",explanations:"Spiegazioni complete",guide:"Study Guide",maps:"Concept Maps",labs:"Interactive Labs",premiumCta:"Scopri Premium"},
  en:{title:"Choose how to prepare",free:"Free",freeBody:"Start free with quizzes, reviews and previews.",dolphin:"Complete theory preparation",octopus:"Theory and interactive practice",premium:"All of CertifyQuiz for learners preparing multiple certifications.",one:"one-time payment",buy:"Choose",upgrade:"Upgrade to Octopus",owned:"Already purchased",inactive:"Dark launch — admin preview only",warning:"This content is already included in Premium. Buy the package only if you want to retain access to this certification after your subscription ends.",buyAnyway:"Buy anyway",noExpiry:"No-expiry access to included content while CertifyQuiz remains available.",quiz:"quizzes",explanations:"Full explanations",guide:"Study Guide",maps:"Concept Maps",labs:"Interactive Labs",premiumCta:"Explore Premium"},
  fr:{title:"Choisissez votre préparation",free:"Gratuit",freeBody:"Commencez gratuitement avec quiz, révisions et aperçus.",dolphin:"Préparation théorique complète",octopus:"Théorie et pratique interactive",premium:"Tout CertifyQuiz pour plusieurs certifications.",one:"paiement unique",buy:"Choisir",upgrade:"Passer à Octopus",owned:"Déjà acheté",inactive:"Lancement privé — aperçu administrateur",warning:"Ce contenu est déjà inclus dans Premium. Achetez le pack uniquement pour conserver cette certification après la fin de l'abonnement.",buyAnyway:"Acheter quand même",noExpiry:"Accès sans expiration aux contenus inclus tant que CertifyQuiz reste disponible.",quiz:"quiz",explanations:"Explications complètes",guide:"Guide d'étude",maps:"Cartes conceptuelles",labs:"Labs interactifs",premiumCta:"Découvrir Premium"},
  es:{title:"Elige cómo prepararte",free:"Gratis",freeBody:"Empieza gratis con cuestionarios, repasos y vistas previas.",dolphin:"Preparación teórica completa",octopus:"Teoría y práctica interactiva",premium:"Todo CertifyQuiz para varias certificaciones.",one:"pago único",buy:"Elegir",upgrade:"Pasar a Octopus",owned:"Ya comprado",inactive:"Lanzamiento privado — vista admin",warning:"Este contenido ya está incluido en Premium. Compra el paquete solo si deseas conservar esta certificación cuando termine la suscripción.",buyAnyway:"Comprar igualmente",noExpiry:"Acceso sin caducidad al contenido incluido mientras CertifyQuiz siga disponible.",quiz:"cuestionarios",explanations:"Explicaciones completas",guide:"Guía de estudio",maps:"Mapas conceptuales",labs:"Labs interactivos",premiumCta:"Ver Premium"}
} as const;

export default function CertificationPackageOffers({lang,certificationSlug,resources}:{lang:Locale;certificationSlug:string;resources:CertificationResources|null}){
  const t=TEXT[lang]; const {user,isAdmin}=useAuth(); const router=useRouter(); const pathname=usePathname();
  const [data,setData]=useState<Payload|null>(null); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let alive=true; apiFetch(`/packages/offers/${encodeURIComponent(certificationSlug)}${isAdmin?"?include_inactive=1":""}`).then(r=>r.ok?r.json():null).then(v=>{if(alive)setData(v)}).catch(()=>{});return()=>{alive=false}},[certificationSlug,isAdmin]);
  const offers=useMemo(()=>data?.offers||[],[data]); if(!offers.length)return null;
  const money=(o:Offer)=>new Intl.NumberFormat(lang==="en"?"en-IE":`${lang}-${lang.toUpperCase()}`,{style:"currency",currency:o.currency}).format((o.effectiveAmountMinor??o.amountMinor)/100);
  const checkout=async(o:Offer)=>{setError(null);if(!user){router.push(`${lang==="en"?"":`/${lang}`}/login?redirect=${encodeURIComponent(pathname||"/")}`);return}if(!o.checkoutAvailable){setError(t.inactive);return}setBusy(o.code);try{await apiFetch("/packages/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:"package_selected",offerCode:o.code,source:"certification_page"})});const r=await apiFetch("/packages/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({offerCode:o.code,lang,source:"certification_page",idempotencyKey:crypto.randomUUID()})});const body=await r.json();if(!r.ok)throw new Error(body.error||"CHECKOUT_FAILED");if(body.url)window.location.href=body.url;}catch(e){setError(e instanceof Error?e.message:"CHECKOUT_FAILED");setBusy(null)}};
  const guidePages=resources?.guide.pageCount||28; const mapCount=resources?.maps.mapCount||10; const labCount=resources?.labs.count||0; const quizCount=resources?.quiz.questionCount||0;
  return <section className="mb-6 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-6" aria-labelledby="package-title">
    <div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 id="package-title" className="text-xl font-black text-slate-950">{t.title}</h2>{data?.darkLaunch&&isAdmin?<span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">{t.inactive}</span>:null}</div>
    {data?.premium?<p className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-950">{t.warning}</p>:null}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <article className="rounded-xl border bg-white p-4"><h3 className="font-black">{t.free}</h3><p className="mt-2 text-sm text-slate-600">{t.freeBody}</p></article>
      {offers.map(o=>{const oct=o.productCode==="octopus-complete";const owned=data?.owned?.tier===o.productCode||data?.owned?.tier==="octopus-complete";return <article key={o.code} className={`rounded-xl border p-4 ${oct?"border-indigo-400 bg-indigo-50":"bg-white"}`}><div className="text-2xl" aria-hidden>{oct?"🐙":"🐬"}</div><h3 className="mt-1 font-black">{o.name}</h3><p className="text-sm text-slate-600">{oct?t.octopus:t.dolphin}</p><p className="mt-3 text-2xl font-black">{money(o)}</p><p className="text-xs font-bold uppercase text-slate-500">{t.one}</p><ul className="mt-3 space-y-1 text-sm">{quizCount>0?<li>✓ {quizCount.toLocaleString(lang)} {t.quiz}</li>:null}<li>✓ {t.explanations}</li>{guidePages>0?<li>✓ {t.guide} · {guidePages}</li>:null}{mapCount>0?<li>✓ {mapCount} {t.maps}</li>:null}{oct&&labCount>0?<li>✓ {labCount} {t.labs}</li>:null}</ul><p className="mt-3 text-xs text-slate-500">{t.noExpiry}</p><button disabled={owned||busy===o.code} onClick={()=>checkout(o)} className="mt-4 min-h-11 w-full rounded-lg bg-slate-950 px-3 font-bold text-white disabled:opacity-50">{owned?t.owned:busy===o.code?"…":data?.premium?t.buyAnyway:(data?.owned?.tier==="dolphin-study"&&oct?t.upgrade:t.buy)}</button></article>})}
      <article className="rounded-xl border border-blue-300 bg-blue-950 p-4 text-white"><div className="text-xl">⭐</div><h3 className="mt-1 font-black">Premium</h3><p className="mt-2 text-sm text-blue-100">{t.premium}</p><a href={pricingPath(lang)} className="mt-4 inline-flex min-h-11 items-center rounded-lg bg-white px-4 font-bold text-blue-950">{t.premiumCta}</a></article>
    </div>{error?<p role="alert" className="mt-3 text-sm font-semibold text-red-700">{error}</p>:null}
  </section>
}
