"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { apiFetch } from "@/lib/auth";
import { certPath, type Locale } from "@/lib/paths";

type Item={entitlement_id:number;status:string;granted_at:string;revoked_at:string|null;revocation_reason:string|null;tier:string;product_name:string;certification_slug:string;certification_name:string;order_id:string;total_minor:number;currency:string;paid_at:string|null;refunded_at:string|null;inclusions:Array<{resource_type:string}>};
const L={it:{title:"I miei pacchetti",empty:"Non hai ancora acquistato pacchetti per singola certificazione.",go:"Continua a studiare",upgrade:"Passa a Octopus",paid:"Pagamento unico",refunded:"Rimborsato"},en:{title:"My packages",empty:"You have not purchased any single-certification packages yet.",go:"Continue studying",upgrade:"Upgrade to Octopus",paid:"One-time payment",refunded:"Refunded"},fr:{title:"Mes packs",empty:"Vous n'avez pas encore acheté de pack pour une certification.",go:"Continuer à étudier",upgrade:"Passer à Octopus",paid:"Paiement unique",refunded:"Remboursé"},es:{title:"Mis paquetes",empty:"Todavía no has comprado paquetes de una certificación.",go:"Seguir estudiando",upgrade:"Pasar a Octopus",paid:"Pago único",refunded:"Reembolsado"}} as const;
export default function MyPackages({lang}:{lang:Locale}){const t=L[lang];const[items,setItems]=useState<Item[]|null>(null);useEffect(()=>{apiFetch("/packages/me").then(r=>r.ok?r.json():null).then(v=>setItems(v?.items||[])).catch(()=>setItems([]))},[]);if(items===null)return null;const quizPrefix=`/${lang}`;return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-slate-900">{t.title}</h2>{items.length===0?<p className="mt-2 text-sm text-slate-600">{t.empty}</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{items.map(x=><article key={x.entitlement_id} className="rounded-xl border bg-slate-50 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase text-slate-500">{x.product_name}</p><h3 className="font-black">{x.certification_name}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${x.status==="active"?"bg-emerald-100 text-emerald-800":"bg-slate-200 text-slate-700"}`}>{x.refunded_at?t.refunded:x.status}</span></div><p className="mt-2 text-xs text-slate-500">{t.paid}{x.paid_at?` · ${new Date(x.paid_at).toLocaleDateString(lang)}`:""}</p><div className="mt-3 flex flex-wrap gap-2">{x.status==="active"?<Link className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white" href={`${quizPrefix}/quiz/${x.certification_slug}`}>{t.go}</Link>:null}{x.status==="active"&&x.tier==="dolphin-study"?<Link className="rounded-lg border px-3 py-2 text-sm font-bold" href={`${certPath(lang,x.certification_slug)}#package-title`}>{t.upgrade}</Link>:null}</div></article>)}</div>}</section>}
