"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { apiFetch } from "@/lib/auth";
import { certPath, type Locale } from "@/lib/paths";
import { activeUntilLabel, formatAccessDate, packageDisplayName } from "@/lib/commercial-packages";

type Item={entitlement_id:number;status:string;granted_at:string;expires_at?:string|null;is_current?:number|boolean;revoked_at:string|null;revocation_reason:string|null;tier:string;product_name:string;certification_slug:string;certification_name:string;order_id:string;total_minor:number;currency:string;paid_at:string|null;refunded_at:string|null;inclusions:Array<{resource_type:string}>};
const L={it:{title:"I miei pacchetti",empty:"Non hai ancora acquistato pacchetti per singola certificazione.",go:"Continua a studiare",upgrade:"Passa a Complete",renew:"Estendi l'accesso",paid:"Pagamento unico",refunded:"Rimborsato",active:"Attivo",expired:"Scaduto",revoked:"Non attivo",expiredOn:(d:string)=>`Scaduto il ${d}`},en:{title:"My packages",empty:"You have not purchased any single-certification packages yet.",go:"Continue studying",upgrade:"Upgrade to Complete",renew:"Extend access",paid:"One-time payment",refunded:"Refunded",active:"Active",expired:"Expired",revoked:"Inactive",expiredOn:(d:string)=>`Expired on ${d}`},fr:{title:"Mes packs",empty:"Vous n'avez pas encore acheté de pack pour une certification.",go:"Continuer à étudier",upgrade:"Passer à Complete",renew:"Prolonger l'accès",paid:"Paiement unique",refunded:"Remboursé",active:"Actif",expired:"Expiré",revoked:"Inactif",expiredOn:(d:string)=>`Expiré le ${d}`},es:{title:"Mis paquetes",empty:"Todavía no has comprado paquetes de una certificación.",go:"Seguir estudiando",upgrade:"Pasar a Complete",renew:"Ampliar acceso",paid:"Pago único",refunded:"Reembolsado",active:"Activo",expired:"Caducado",revoked:"Inactivo",expiredOn:(d:string)=>`Caducó el ${d}`}} as const;

export default function MyPackages({lang}:{lang:Locale}){const t=L[lang];const[items,setItems]=useState<Item[]|null>(null);useEffect(()=>{apiFetch("/packages/me").then(r=>r.ok?r.json():null).then(v=>setItems(v?.items||[])).catch(()=>setItems([]))},[]);if(items===null)return null;const quizPrefix=`/${lang}`;return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-slate-900">{t.title}</h2>{items.length===0?<p className="mt-2 text-sm text-slate-600">{t.empty}</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{items.map(x=>{
  // is_current arriva dal backend (status attivo e non scaduto); fallback per risposte pre-Phase 4.
  const current=x.is_current===undefined?x.status==="active":!!Number(x.is_current);
  const expired=x.status==="active"&&!current;
  const badge=x.refunded_at?t.refunded:current?t.active:expired?t.expired:t.revoked;
  const note=current?activeUntilLabel(x.expires_at,lang):expired&&formatAccessDate(x.expires_at,lang)?t.expiredOn(formatAccessDate(x.expires_at,lang) as string):null;
  const packagesHref=`${certPath(lang,x.certification_slug)}#packages`;
  return <article key={x.entitlement_id} className="rounded-xl border bg-slate-50 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-black">{packageDisplayName(x.tier,x.certification_name,lang)}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${current?"bg-emerald-100 text-emerald-800":"bg-slate-200 text-slate-700"}`}>{badge}</span></div><p className="mt-2 text-xs text-slate-500">{t.paid}{x.paid_at?` · ${new Date(x.paid_at).toLocaleDateString(lang)}`:""}</p>{note?<p className="mt-1 text-xs font-semibold text-slate-700">{note}</p>:null}<div className="mt-3 flex flex-wrap gap-2">{current?<Link className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white" href={`${quizPrefix}/quiz/${x.certification_slug}`}>{t.go}</Link>:null}{current&&x.tier==="dolphin-study"?<Link className="rounded-lg border px-3 py-2 text-sm font-bold" href={packagesHref}>{t.upgrade}</Link>:null}{x.expires_at&&(current||expired)&&!x.refunded_at&&x.tier==="octopus-complete"?<Link className="rounded-lg border px-3 py-2 text-sm font-bold" href={packagesHref}>{t.renew}</Link>:null}</div></article>})}</div>}</section>}
