"use client";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
import type { Locale } from "@/lib/i18n";
import { certPath } from "@/lib/paths";
import { trackEvent } from "@/lib/analytics";
import { GAME_DURATION_MS } from "../binary-rush/logic";
import { portAndTransport } from "./data";
import { makeQuestion,scorePortAnswer,validatePort } from "./logic";
import { loadPortStorage,savePortPreferences,savePortResult } from "./storage";
import { portText } from "./content";
import type { PortDifficulty,PortMode,PortQuestion } from "./types";

type Phase="intro"|"playing"|"finished"; type Feedback={ok:boolean}|null;
type Result={score:number;correct:number;wrong:number;maxCombo:number;mode:PortMode;difficulty:PortDifficulty;isNewRecord:boolean};
export default function PortHunterGame({lang}:{lang:Locale}){
 const t=portText[lang];const [phase,setPhase]=useState<Phase>("intro"),[mode,setMode]=useState<PortMode>("mixed"),[difficulty,setDifficulty]=useState<PortDifficulty>("basic"),[best,setBest]=useState(0);
 const [hydrated,setHydrated]=useState(false);
 const [question,setQuestion]=useState<PortQuestion|null>(null),[answer,setAnswer]=useState(""),[remaining,setRemaining]=useState(GAME_DURATION_MS),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[correct,setCorrect]=useState(0),[wrong,setWrong]=useState(0),[maxCombo,setMaxCombo]=useState(0),[feedback,setFeedback]=useState<Feedback>(null),[result,setResult]=useState<Result|null>(null),[shared,setShared]=useState(false);
 const endAt=useRef(0),questionAt=useRef(0),locked=useRef(false),feedbackTimer=useRef<number|null>(null),inputRef=useRef<HTMLInputElement>(null);
 const modeRef=useRef<PortMode>("mixed"),difficultyRef=useRef<PortDifficulty>("basic");
 useEffect(()=>{setHydrated(true);const s=loadPortStorage();setBest(s.bestOverall);setMode(s.lastMode);modeRef.current=s.lastMode;setDifficulty(s.lastDifficulty);difficultyRef.current=s.lastDifficulty;trackEvent("game_viewed",{game_name:"port_hunter"});return()=>{if(feedbackTimer.current)window.clearTimeout(feedbackTimer.current);};},[]);
 const finish=useCallback(()=>{if(phase!=="playing")return;const saved=savePortResult(mode,difficulty,score),total=correct+wrong,accuracy=total?Math.round(correct/total*100):0;const r={score,correct,wrong,maxCombo,mode,difficulty,isNewRecord:saved.isNewRecord};setResult(r);setBest(saved.data.bestOverall);setRemaining(0);setPhase("finished");locked.current=true;trackEvent("game_completed",{game_name:"port_hunter",mode,difficulty,score,accuracy,correct_answers:correct,max_combo:maxCombo,is_new_record:saved.isNewRecord});},[phase,mode,difficulty,score,correct,wrong,maxCombo]);
 useEffect(()=>{if(phase!=="playing")return;const tick=()=>{const left=Math.max(0,endAt.current-Date.now());setRemaining(left);if(left===0)finish();};tick();const id=window.setInterval(tick,100);return()=>window.clearInterval(id);},[phase,finish]);
 const modeLabel=(v:PortMode)=>v==="mixed"?t.mixed:v==="service-to-port"?t.s2p:t.p2s;const difficultyLabel=(v:PortDifficulty)=>v==="basic"?t.basic:v==="intermediate"?t.intermediate:t.advanced;
 function start(restarted=false){if(feedbackTimer.current)clearTimeout(feedbackTimer.current);const selectedMode=modeRef.current,selectedDifficulty=difficultyRef.current,now=Date.now();endAt.current=now+GAME_DURATION_MS;questionAt.current=now;locked.current=false;setScore(0);setCombo(0);setCorrect(0);setWrong(0);setMaxCombo(0);setFeedback(null);setAnswer("");setRemaining(GAME_DURATION_MS);setResult(null);setQuestion(makeQuestion(selectedMode,selectedDifficulty));setPhase("playing");savePortPreferences(selectedMode,selectedDifficulty);trackEvent(restarted?"game_restarted":"game_started",{game_name:"port_hunter",mode:selectedMode,difficulty:selectedDifficulty});setTimeout(()=>inputRef.current?.focus(),0);}
 function submit(selected?:string){if(!question||locked.current||Date.now()>=endAt.current)return;const value=selected??answer;if(!value.trim())return;locked.current=true;const ok=question.direction==="service-to-port"?validatePort(question.entry,value):value===question.entry.id;const nextCombo=ok?combo+1:0;setFeedback({ok});if(ok){setCorrect(v=>v+1);setCombo(nextCombo);setMaxCombo(v=>Math.max(v,nextCombo));setScore(v=>v+scorePortAnswer(nextCombo,Date.now()-questionAt.current,difficulty));}else{setWrong(v=>v+1);setCombo(0);}feedbackTimer.current=window.setTimeout(()=>{if(Date.now()>=endAt.current)return;setQuestion(q=>makeQuestion(mode,difficulty,q??undefined));setAnswer("");setFeedback(null);questionAt.current=Date.now();locked.current=false;setTimeout(()=>inputRef.current?.focus(),0);},700);}
 async function share(){if(!result)return;const total=result.correct+result.wrong,accuracy=total?Math.round(result.correct/total*100):0,text=`${t.shareText(result.score,accuracy,difficultyLabel(result.difficulty))} ${location.href}`;try{if(navigator.share)await navigator.share({title:"Port Hunter",text,url:location.href});else await navigator.clipboard.writeText(text);setShared(true);trackEvent("game_result_shared",{game_name:"port_hunter",mode:result.mode,difficulty:result.difficulty,score:result.score,accuracy});}catch{}}
 const accuracy=result&&result.correct+result.wrong?Math.round(result.correct/(result.correct+result.wrong)*100):0;
 return <main id="main" className="mx-auto max-w-4xl px-4 py-8 sm:py-12"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-950"><header className="border-b border-slate-200 bg-gradient-to-r from-slate-950 to-emerald-950 p-6 text-white"><p className="font-mono text-xs uppercase tracking-[.25em] text-emerald-300">CertifyQuiz Labs</p><h1 className="mt-2 font-mono text-3xl font-bold sm:text-4xl">Port Hunter</h1><p className="mt-2 text-slate-200">{t.desc}</p></header>
 {phase==="intro"&&<section className="p-6 sm:p-8"><h2 className="text-xl font-bold">{t.rules}</h2><Choice title={t.mode} values={(["mixed","service-to-port","port-to-service"] as PortMode[])} selected={mode} set={v=>{modeRef.current=v;setMode(v);}} label={modeLabel}/><Choice title={t.difficulty} values={(["basic","intermediate","advanced"] as PortDifficulty[])} selected={difficulty} set={v=>{difficultyRef.current=v;setDifficulty(v);}} label={difficultyLabel}/><div className="mt-7 flex flex-wrap items-center gap-4"><button disabled={!hydrated} onClick={()=>start()} className="min-h-12 rounded-lg bg-emerald-700 px-7 py-3 font-bold text-white hover:bg-emerald-800 focus:ring-2 focus:ring-emerald-500 disabled:cursor-wait disabled:opacity-60">{t.start}</button>{best>0&&<p><span className="text-gray-500">{t.best}:</span> <strong>{best}</strong></p>}</div></section>}
 {phase==="playing"&&question&&<section className="p-4 sm:p-8"><div className="grid grid-cols-5 gap-2 text-center">{[[t.time,Math.ceil(remaining/1000)],[t.score,score],[t.combo,`×${combo}`],[t.correct,correct],[t.difficulty,difficultyLabel(difficulty)]].map(([l,v])=><div key={String(l)} className="rounded-lg bg-slate-100 p-2 dark:bg-slate-900"><div className="text-xs text-gray-500">{l}</div><div className="font-mono text-base font-bold sm:text-xl">{v}</div></div>)}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-label={t.time} aria-valuemin={0} aria-valuemax={60} aria-valuenow={Math.ceil(remaining/1000)}><div className="h-full bg-emerald-500 transition-[width] duration-100 motion-reduce:transition-none" style={{width:`${remaining/GAME_DURATION_MS*100}%`}}/></div><div className="mt-8 min-h-72 text-center"><p className="text-sm font-semibold uppercase tracking-wide text-gray-500">{question.direction==="service-to-port"?t.questionS2p:t.questionP2s}</p><div className="my-5 font-mono text-4xl font-black sm:text-5xl">{question.direction==="service-to-port"?question.entry.service:question.entry.ports[0]}</div>{question.direction==="service-to-port"?<form onSubmit={e=>{e.preventDefault();submit();}} className="mx-auto flex max-w-md gap-2"><label className="sr-only" htmlFor="port-answer">{t.answer}</label><input ref={inputRef} id="port-answer" inputMode="numeric" pattern="[0-9]*" value={answer} onChange={e=>setAnswer(e.target.value.replace(/\D/g,"").slice(0,5))} disabled={!!feedback} className="min-h-12 min-w-0 flex-1 rounded-lg border-2 px-4 text-center font-mono text-2xl focus:border-emerald-500 focus:outline-none"/><button disabled={!!feedback||!answer} className="min-h-12 rounded-lg bg-emerald-700 px-5 font-bold text-white disabled:opacity-50">{t.submit}</button></form>:<div className="mx-auto grid max-w-xl grid-cols-1 gap-3 sm:grid-cols-2">{question.options.map(o=><button key={o.id} disabled={!!feedback} onClick={()=>submit(o.id)} className="min-h-14 rounded-xl border-2 p-3 font-semibold hover:border-emerald-500 focus:ring-2 focus:ring-emerald-500 disabled:opacity-60">{o.service}</button>)}</div>}<div aria-live="polite" className="mt-5 min-h-20">{feedback&&<p className={`font-semibold ${feedback.ok?"text-emerald-700":"text-red-700"}`}><span aria-hidden>{feedback.ok?"✓":"✕"}</span> {feedback.ok?t.right:`${t.wrong}. ${t.correctAnswer}: ${question.entry.service} — ${portAndTransport(question.entry)}`}<br/><span className="text-sm font-normal text-gray-600 dark:text-gray-300">{question.entry.description[lang]} {t.transport}: {question.entry.transports.join(" + ")}.</span></p>}</div></div></section>}
 {phase==="finished"&&result&&<section className="p-6 text-center sm:p-8"><h2 className="text-2xl font-bold">{t.final}</h2>{result.isNewRecord&&<p className="mt-2 font-bold text-emerald-600">★ {t.newRecord}</p>}<p className="mt-5 font-mono text-5xl font-black">{result.score}</p><p className="mt-2">{modeLabel(result.mode)} · {difficultyLabel(result.difficulty)}</p><div className="mx-auto mt-6 grid max-w-lg grid-cols-2 gap-3 sm:grid-cols-4">{[[t.correct,result.correct],[t.errors,result.wrong],[t.accuracy,`${accuracy}%`],[t.maxCombo,result.maxCombo]].map(([l,v])=><div key={String(l)} className="rounded-lg bg-slate-100 p-3 dark:bg-slate-900"><div className="text-xs text-gray-500">{l}</div><strong>{v}</strong></div>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={()=>start(true)} className="min-h-11 rounded-lg bg-emerald-700 px-5 font-bold text-white">{t.again}</button><button onClick={()=>setPhase("intro")} className="min-h-11 rounded-lg border px-5 font-semibold">{t.change}</button><button onClick={share} className="min-h-11 rounded-lg border px-5 font-semibold">{t.share}</button></div>{shared&&<p role="status" className="mt-3 text-sm text-emerald-700">{t.copied}</p>}<div className="mt-8 border-t pt-6"><p>{t.cta}</p><div className="mt-3 flex justify-center gap-5"><Cta lang={lang} slug="ccna" label={t.ctaCcna}/><Cta lang={lang} slug="cisco-ccst-networking" label={t.ctaCcst}/></div></div></section>}
 </div></main>;
}
function Choice<T extends string>({title,values,selected,set,label}:{title:string;values:readonly T[];selected:T;set:(v:T)=>void;label:(v:T)=>string}){return <fieldset className="mt-6"><legend className="mb-3 font-semibold">{title}</legend><div className="grid gap-3 sm:grid-cols-3">{values.map(v=><label key={v} className={`cursor-pointer rounded-xl border p-4 text-center font-semibold ${selected===v?"border-emerald-600 bg-emerald-50 ring-2 ring-emerald-200 dark:bg-emerald-950":"hover:bg-gray-50 dark:hover:bg-slate-900"}`}><input className="sr-only" type="radio" name={title} checked={selected===v} onChange={()=>set(v)}/>{label(v)}</label>)}</div></fieldset>}
function Cta({lang,slug,label}:{lang:Locale;slug:string;label:string}){return <Link onClick={()=>trackEvent("game_cta_clicked",{game_name:"port_hunter",destination:slug})} href={certPath(lang,slug)} className="font-bold text-emerald-700 underline underline-offset-4">{label} →</Link>}
