"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import type{Locale}from"@/lib/i18n";
import{certPath}from"@/lib/paths";
import{trackEvent}from"@/lib/analytics";
import{hexText}from"./content";
import{generateHexQuestion,hexExplanation,HEX_DURATION_MS,hexScore,isHexCorrect}from"./logic";
import{loadHexStorage,saveHexMode,saveHexResult}from"./storage";
import type{HexMode,HexQuestion,HexResult}from"./types";

type Phase="intro"|"playing"|"finished";type Feedback={ok:boolean;explanation:string}|null;
export default function HexBlitzGame({lang}:{lang:Locale}){const t=hexText[lang];
 const[phase,setPhase]=useState<Phase>("intro"),[mode,setMode]=useState<HexMode>("mixed"),[best,setBest]=useState(0),[question,setQuestion]=useState<HexQuestion|null>(null),[answer,setAnswer]=useState(""),[remaining,setRemaining]=useState(HEX_DURATION_MS),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[correct,setCorrect]=useState(0),[wrong,setWrong]=useState(0),[maxCombo,setMaxCombo]=useState(0),[feedback,setFeedback]=useState<Feedback>(null),[result,setResult]=useState<HexResult|null>(null),[shared,setShared]=useState(false);
 const endAt=useRef(0),startedAt=useRef(0),questionAt=useRef(0),locked=useRef(false),inputRef=useRef<HTMLInputElement>(null),modeRef=useRef<HexMode>("mixed");
 useEffect(()=>{const s=loadHexStorage();setBest(s.bestOverall);setMode(s.lastMode);modeRef.current=s.lastMode;trackEvent("game_viewed",{game_name:"hex_blitz"});},[]);
 const finish=useCallback(()=>{if(phase!=="playing")return;const saved=saveHexResult(modeRef.current,score),total=correct+wrong,accuracy=total?Math.round(correct/total*100):0,r={score,correct,wrong,maxCombo,mode:modeRef.current,isNewRecord:saved.isNewRecord};setResult(r);setBest(saved.data.bestOverall);setRemaining(0);setPhase("finished");locked.current=true;trackEvent("game_completed",{game_name:"hex_blitz",mode:modeRef.current,score,accuracy,correct_answers:correct,max_combo:maxCombo});},[phase,score,correct,wrong,maxCombo]);
 useEffect(()=>{if(phase!=="playing")return;const tick=()=>{const left=Math.max(0,endAt.current-Date.now());setRemaining(left);if(!left)finish();};tick();const id=window.setInterval(tick,100);return()=>clearInterval(id);},[phase,finish]);
 function start(restarted=false){const now=Date.now(),selected=modeRef.current;startedAt.current=now;endAt.current=now+HEX_DURATION_MS;questionAt.current=now;locked.current=false;setScore(0);setCombo(0);setCorrect(0);setWrong(0);setMaxCombo(0);setFeedback(null);setAnswer("");setRemaining(HEX_DURATION_MS);setResult(null);setQuestion(generateHexQuestion(selected,0));setPhase("playing");saveHexMode(selected);trackEvent(restarted?"game_restarted":"game_started",{game_name:"hex_blitz",mode:selected});setTimeout(()=>inputRef.current?.focus(),0);}
 function submit(){if(!question||locked.current||!answer.trim()||Date.now()>=endAt.current)return;locked.current=true;const ok=isHexCorrect(question,answer),next=ok?combo+1:0;setFeedback({ok,explanation:hexExplanation(question.value)});if(ok){setCorrect(v=>v+1);setCombo(next);setMaxCombo(v=>Math.max(v,next));setScore(v=>v+hexScore(next,Date.now()-questionAt.current));}else{setWrong(v=>v+1);setCombo(0);}setTimeout(()=>{if(Date.now()>=endAt.current)return;setQuestion(q=>generateHexQuestion(modeRef.current,Date.now()-startedAt.current,q??undefined));setAnswer("");setFeedback(null);questionAt.current=Date.now();locked.current=false;inputRef.current?.focus();},650);}
 async function share(){if(!result)return;const text=`Hex Blitz — ${result.score} points on CertifyQuiz! ${location.href}`;try{if(navigator.share)await navigator.share({title:"Hex Blitz",text,url:location.href});else await navigator.clipboard.writeText(text);setShared(true);}catch{}}
 const label=(m:HexMode)=>m==="mixed"?t.mixed:m==="hex-to-decimal"?t.h2d:t.d2h,accuracy=result&&result.correct+result.wrong?Math.round(result.correct/(result.correct+result.wrong)*100):0;
 return <main id="main" className="mx-auto max-w-4xl px-4 py-8 sm:py-12"><div className="overflow-hidden rounded-2xl border border-violet-200 bg-white shadow-xl dark:border-violet-900 dark:bg-slate-950"><header className="border-b border-violet-800 bg-gradient-to-r from-slate-950 via-violet-950 to-fuchsia-950 p-6 text-white"><p className="font-mono text-xs uppercase tracking-[.25em] text-fuchsia-300">CertifyQuiz Labs</p><h1 className="mt-2 font-mono text-3xl font-bold sm:text-4xl">Hex Blitz</h1><p className="mt-2 text-slate-200">{t.intro}</p></header>
 {phase==="intro"&&<section className="p-6 sm:p-8"><h2 className="text-xl font-bold">{t.rules}</h2><fieldset className="mt-6"><legend className="mb-3 font-semibold">{t.mode}</legend><div className="grid gap-3 sm:grid-cols-3">{(["mixed","hex-to-decimal","decimal-to-hex"]as HexMode[]).map(m=><label key={m} className={`cursor-pointer rounded-xl border p-4 text-center font-semibold ${mode===m?"border-violet-600 bg-violet-50 ring-2 ring-violet-200 dark:bg-violet-950":"hover:bg-gray-50 dark:hover:bg-slate-900"}`}><input className="sr-only" type="radio" name="mode" checked={mode===m} onChange={()=>{setMode(m);modeRef.current=m;}}/>{label(m)}</label>)}</div></fieldset><div className="mt-7 flex items-center gap-4"><button onClick={()=>start()} className="min-h-12 rounded-lg bg-violet-700 px-7 py-3 font-bold text-white hover:bg-violet-800">{t.start}</button>{best>0&&<p><span className="text-gray-500">{t.best}: </span><b>{best}</b></p>}</div></section>}
 {phase==="playing"&&question&&<section className="p-4 sm:p-8"><div className="grid grid-cols-4 gap-2 text-center">{[[t.time,Math.ceil(remaining/1000)],[t.score,score],[t.combo,`×${combo}`],[t.correct,correct]].map(([l,v])=><div key={String(l)} className="rounded-lg bg-slate-100 p-2 dark:bg-slate-900"><div className="text-xs text-gray-500">{l}</div><div className="font-mono text-xl font-bold">{v}</div></div>)}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200" role="progressbar" aria-label={t.time} aria-valuemax={60} aria-valuemin={0} aria-valuenow={Math.ceil(remaining/1000)}><div className="h-full bg-fuchsia-500" style={{width:`${remaining/HEX_DURATION_MS*100}%`}}/></div><div className="mt-8 min-h-44 text-center"><p className="text-sm font-semibold uppercase tracking-wide text-gray-500">{question.direction==="hex-to-decimal"?t.questionH2d:t.questionD2h}</p><div className="my-5 font-mono text-5xl font-black tracking-wider sm:text-6xl">{question.prompt}<sub className="text-lg">{question.direction==="hex-to-decimal"?"16":"10"}</sub></div><form onSubmit={e=>{e.preventDefault();submit();}} className="mx-auto flex max-w-md gap-2"><label className="sr-only" htmlFor="hex-answer">{t.answer}</label><input ref={inputRef} id="hex-answer" inputMode={question.direction==="hex-to-decimal"?"numeric":"text"} value={answer} onChange={e=>setAnswer(e.target.value.replace(question.direction==="hex-to-decimal"?/\D/g:/[^0-9a-f]/gi,"").toUpperCase())} disabled={!!feedback} autoComplete="off" className="min-h-12 min-w-0 flex-1 rounded-lg border-2 px-4 text-center font-mono text-2xl uppercase focus:border-violet-500 focus:outline-none"/><button disabled={!!feedback||!answer} className="min-h-12 rounded-lg bg-violet-700 px-5 font-bold text-white disabled:opacity-50">{t.submit}</button></form><div aria-live="polite" className="mt-4 min-h-14">{feedback&&<p className={`font-semibold ${feedback.ok?"text-emerald-700":"text-red-700"}`}>{feedback.ok?t.right:`${t.wrong}. ${t.correctAnswer}: ${question.answer}`}<br/><span className="font-mono text-sm text-gray-600 dark:text-gray-300">{feedback.explanation}</span></p>}</div></div></section>}
 {phase==="finished"&&result&&<section className="p-6 text-center sm:p-8"><h2 className="text-2xl font-bold">{t.finished}</h2>{result.isNewRecord&&<p className="mt-2 font-bold text-fuchsia-600">★ {t.record}</p>}<p className="mt-5 font-mono text-5xl font-black">{result.score}</p><div className="mx-auto mt-6 grid max-w-lg grid-cols-2 gap-3 sm:grid-cols-4">{[[t.correct,result.correct],[t.errors,result.wrong],[t.accuracy,`${accuracy}%`],[t.maxCombo,result.maxCombo]].map(([l,v])=><div key={String(l)} className="rounded-lg bg-slate-100 p-3 dark:bg-slate-900"><small className="block text-gray-500">{l}</small><b>{v}</b></div>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={()=>start(true)} className="min-h-11 rounded-lg bg-violet-700 px-5 font-bold text-white">{t.again}</button><button onClick={()=>setPhase("intro")} className="min-h-11 rounded-lg border px-5 font-semibold">{t.change}</button><button onClick={share} className="min-h-11 rounded-lg border px-5 font-semibold">{t.share}</button></div>{shared&&<p role="status" className="mt-3 text-emerald-700">{t.copied}</p>}<div className="mt-8 border-t pt-6"><p>{t.cta}</p><Link href={certPath(lang,"comptia-a-plus-core-1-220-1101")} className="font-bold text-violet-700 underline">{t.ctaButton} →</Link></div></section>}</div></main>;
}
