import type { Locale } from "@/lib/i18n";

export const gameText = {
  it: { indexTitle:"Giochi informatici", indexIntro:"Impara concetti IT con sfide brevi, gratuite e coinvolgenti.", available:"Disponibile", free:"Gratis", play:"Gioca ora", soon:"Prossimamente", binaryDesc:"Converti numeri binari e decimali contro il tempo.", intro:"Quante conversioni riesci a completare in 60 secondi?", rules:"Converti il numero mostrato. Rispondi velocemente per ottenere bonus e crea una combo con risposte consecutive.", mode:"Modalità", mixed:"Mista", b2d:"Binario → Decimale", d2b:"Decimale → Binario", start:"Inizia", best:"Record personale", time:"Tempo", score:"Punteggio", combo:"Combo", correct:"Corrette", answer:"La tua risposta", submit:"Conferma", right:"Corretto!", wrong:"Non corretto", correctAnswer:"Risposta corretta", final:"Partita terminata", errors:"Sbagliate", accuracy:"Precisione", maxCombo:"Combo massima", newRecord:"Nuovo record!", again:"Gioca ancora", change:"Cambia modalità", share:"Condividi risultato", copied:"Risultato copiato negli appunti", cta:"Continua ad allenare le competenze di networking", ctaButton:"Scopri CCNA", questionB2d:"Converti in decimale", questionD2b:"Converti in binario", shareText:(s:number)=>`Binary Rush — ho totalizzato ${s} punti su CertifyQuiz!` },
  en: { indexTitle:"IT learning games", indexIntro:"Learn IT concepts through short, free and engaging challenges.", available:"Available", free:"Free", play:"Play now", soon:"Coming soon", binaryDesc:"Convert binary and decimal numbers against the clock.", intro:"How many conversions can you complete in 60 seconds?", rules:"Convert the number shown. Answer quickly for a speed bonus and build a combo with consecutive correct answers.", mode:"Mode", mixed:"Mixed", b2d:"Binary → Decimal", d2b:"Decimal → Binary", start:"Start", best:"Personal best", time:"Time", score:"Score", combo:"Combo", correct:"Correct", answer:"Your answer", submit:"Submit", right:"Correct!", wrong:"Not quite", correctAnswer:"Correct answer", final:"Time's up", errors:"Wrong", accuracy:"Accuracy", maxCombo:"Max combo", newRecord:"New record!", again:"Play again", change:"Change mode", share:"Share result", copied:"Result copied to clipboard", cta:"Keep building your networking skills", ctaButton:"Explore CCNA", questionB2d:"Convert to decimal", questionD2b:"Convert to binary", shareText:(s:number)=>`Binary Rush — I scored ${s} points on CertifyQuiz!` },
  fr: { indexTitle:"Jeux informatiques éducatifs", indexIntro:"Apprenez l’informatique avec des défis courts, gratuits et captivants.", available:"Disponible", free:"Gratuit", play:"Jouer", soon:"Bientôt", binaryDesc:"Convertissez des nombres binaires et décimaux contre la montre.", intro:"Combien de conversions pouvez-vous réussir en 60 secondes ?", rules:"Convertissez le nombre affiché. Répondez vite pour gagner un bonus et enchaînez les bonnes réponses.", mode:"Mode", mixed:"Mixte", b2d:"Binaire → Décimal", d2b:"Décimal → Binaire", start:"Commencer", best:"Meilleur score", time:"Temps", score:"Score", combo:"Combo", correct:"Correctes", answer:"Votre réponse", submit:"Valider", right:"Correct !", wrong:"Incorrect", correctAnswer:"Bonne réponse", final:"Temps écoulé", errors:"Incorrectes", accuracy:"Précision", maxCombo:"Combo maximale", newRecord:"Nouveau record !", again:"Rejouer", change:"Changer de mode", share:"Partager", copied:"Résultat copié", cta:"Continuez à développer vos compétences réseau", ctaButton:"Découvrir CCNA", questionB2d:"Convertissez en décimal", questionD2b:"Convertissez en binaire", shareText:(s:number)=>`Binary Rush — j’ai obtenu ${s} points sur CertifyQuiz !` },
  es: { indexTitle:"Juegos educativos de informática", indexIntro:"Aprende informática con retos breves, gratuitos y entretenidos.", available:"Disponible", free:"Gratis", play:"Jugar", soon:"Próximamente", binaryDesc:"Convierte números binarios y decimales contrarreloj.", intro:"¿Cuántas conversiones puedes completar en 60 segundos?", rules:"Convierte el número mostrado. Responde rápido para ganar un bonus y encadena respuestas correctas.", mode:"Modo", mixed:"Mixta", b2d:"Binario → Decimal", d2b:"Decimal → Binario", start:"Empezar", best:"Récord personal", time:"Tiempo", score:"Puntuación", combo:"Combo", correct:"Correctas", answer:"Tu respuesta", submit:"Confirmar", right:"¡Correcto!", wrong:"Incorrecto", correctAnswer:"Respuesta correcta", final:"Tiempo terminado", errors:"Incorrectas", accuracy:"Precisión", maxCombo:"Combo máxima", newRecord:"¡Nuevo récord!", again:"Jugar de nuevo", change:"Cambiar modo", share:"Compartir", copied:"Resultado copiado", cta:"Sigue mejorando tus habilidades de redes", ctaButton:"Descubre CCNA", questionB2d:"Convierte a decimal", questionD2b:"Convierte a binario", shareText:(s:number)=>`Binary Rush — ¡he conseguido ${s} puntos en CertifyQuiz!` },
} satisfies Record<Locale, Record<string, unknown>>;

export type GameText = typeof gameText.it;
