import type { SalesforceEditorialQuestion } from "./salesforce-editorial-types";

type Q = SalesforceEditorialQuestion<"objects-relationships-lightning-app-builder", "CS-02" | "OM-01" | "OM-02" | "OM-03">;

export const SALESFORCE_PLATFORM_ADMIN_TOPIC_04_SOURCES = [
  { title: "Salesforce Certified Platform Administrator Exam Guide", url: "https://help.salesforce.com/s/articleView?id=005298966&type=1&language=en_US", lastVerifiedAt: "2026-08-20", objectiveIds: ["CS-02", "OM-01", "OM-02", "OM-03"] },
  { title: "Data Modeling", url: "https://trailhead.salesforce.com/content/learn/modules/data_modeling", lastVerifiedAt: "2026-08-20", objectiveIds: ["OM-01", "OM-02"] },
  { title: "Create Object Relationships", url: "https://trailhead.salesforce.com/content/learn/modules/data_modeling/object_relationships", lastVerifiedAt: "2026-08-20", objectiveIds: ["OM-01", "OM-02"] },
  { title: "Get Help for Lightning App Builder", url: "https://help.salesforce.com/s/articleView?id=sf.lightning_app_builder_overview.htm&language=en_US", lastVerifiedAt: "2026-08-20", objectiveIds: ["CS-02", "OM-03"] },
] as const;

export const SALESFORCE_PLATFORM_ADMIN_TOPIC_04_REVIEW = {
  id: "SF-PA-T04-REVIEW-EN", language: "en", topicSlug: "objects-relationships-lightning-app-builder",
  title: "Objects, Relationships, and Lightning App Builder — Exam Review",
  objectiveIds: ["CS-02", "OM-01", "OM-02", "OM-03"], blueprintDomains: ["Object Manager and Lightning App Builder", "Configuration and Setup", "Data and Analytics Management"],
  lastVerifiedAt: "2026-08-20", sourceUrls: SALESFORCE_PLATFORM_ADMIN_TOPIC_04_SOURCES.map((source) => source.url),
  content: `## Learning objectives

This review prepares you to translate a business requirement into a maintainable Salesforce data model and declarative user experience. Topic 4 owns **CS-02**, **OM-01**, **OM-02**, and **OM-03**. Security remains Topic 3: a page can present a field, but object permission and field-level security still decide whether a user can access it. Automation belongs primarily to Topic 10.

## Objects and fields

Use a standard object when its meaning and lifecycle match the business concept. Account, Contact, Opportunity, Lead, Case, Campaign, Product, and other standard objects bring platform behavior and relationships that a look-alike custom object would duplicate. Create a custom object when the organization must store a distinct, repeatable business entity that has its own records, fields, relationships, ownership, reporting, and lifecycle. Do not create an object merely to hold one additional attribute; a field on an existing object may be sufficient.

Choose field types from the required behavior. Picklists constrain values, checkboxes represent binary states, dates and date-times preserve temporal meaning, currency and number fields support numeric behavior, and formulas derive a value rather than storing user input. A formula recalculates from referenced data; it is not a historical snapshot. Field dependencies guide compatible controlling and dependent picklist values. Before changing or deleting a field, assess data, formulas, reports, integrations, layouts, and automation that reference it.

## Relationship decisions

A lookup relationship is the looser association. Related records can generally retain independent ownership and lifecycle, and the relationship can be optional when configured that way. Choose lookup when the child must stand alone or when deleting a parent must not automatically delete related records.

A master-detail relationship expresses dependency. The detail record is controlled by the master for ownership and sharing behavior, and deleting the master deletes its detail records. The relationship field is created on the detail object. Master-detail also enables roll-up summary fields on the master for supported aggregate calculations over detail records. Choose it only when those lifecycle and control implications are truly required.

A many-to-many design uses a junction object, normally with two master-detail relationships, when each record on either side can relate to many records on the other. The junction record can also carry attributes about the association itself. Avoid forcing multiple IDs into text or proliferating repeated lookup fields.

### Relationship decision rule

Ask: Can the related record exist without the parent? Must ownership and visibility follow the parent? Is cascade deletion acceptable? Is a native roll-up summary required? If independence matters, prefer lookup. If dependency is fundamental, master-detail may fit. Always evaluate existing data and downstream dependencies before changing a relationship type.

## Record types, business processes, and page layouts

Record types can provide different business processes, picklist value subsets, and page-layout assignments for different categories of records. They do not grant object or record access. Use them when users genuinely follow distinct processes or require controlled value sets, not simply to rename the same experience.

Page layouts control the arrangement of record details, related lists, buttons, and actions, and can mark fields required or read-only at the layout layer. Layout-required behavior is an interface requirement, not a universal data-integrity control for every API or automation path. Field-level security is the security boundary for field visibility and editability.

Business processes constrain relevant status or stage values for objects such as Lead, Opportunity, Case, and Solution and are associated through record types. Diagnose the full chain: assigned record type, associated process, available picklist values, and page-layout assignment.

## Lightning App Builder

Lightning App Builder is the point-and-click tool for composing Lightning pages with components. An app page provides a standalone experience, a home page targets an app/home context, and a record page customizes the record experience for an object. Record pages can be activated as an org default, app default, or for selected app, record type, and profile combinations where supported.

Component visibility rules conditionally show a component based on supported criteria. This improves relevance but is not a security control: hidden presentation does not revoke object, field, or record access. Dynamic forms can place supported fields and field sections as components and apply visibility rules, but administrators must verify object and form-factor support rather than assuming every page behaves identically.

Use page layouts for detail organization, actions, related lists, and layout assignment. Use Lightning record pages for component composition, placement, and conditional experience. Use field-level security and sharing for access. When a user sees the wrong page, inspect activation and assignment before rebuilding the page.

## Declarative user-experience decisions

Apps organize navigation around a job. Tabs expose objects or content in that navigation, list views provide filtered working sets, and actions give users focused record operations. Choose the narrowest configuration that satisfies the workflow. A missing navigation item can be an app configuration issue; a missing object can instead be permission or license related. Distinguish presentation from authorization.

For multiple personas, first ask whether the underlying process, values, or layout actually differs. Record types plus page-layout assignments suit stable process variants. Lightning page activation and component visibility suit contextual page composition. Separate custom objects are appropriate only for genuinely different entities, not merely different audiences.

## Troubleshooting the model and UI

Start from metadata and reproduce the user's context. For unexpected values, inspect field type, dependencies, record type, and business process. For an unexpected layout, inspect record type assignment and page-layout mapping. For an unexpected Lightning page, inspect activation by app, profile, record type, and form factor. For missing data, then cross the boundary to object permission, field-level security, and record sharing.

Before destructive schema changes, identify references and data consequences. Master-detail cascade deletion and relationship conversion are especially sensitive. Prototype material changes, test with representative users and records, and preserve a rollback or migration plan.

## Mini-scenarios

**Independent inspections:** Inspections may remain after a Facility is retired and have their own owner. Use lookup rather than master-detail.

**Dependent invoice lines:** A line has no meaning without its invoice, must inherit control, and totals must roll up. Master-detail is the natural candidate after confirming deletion behavior.

**Two sales motions:** Enterprise and retail opportunities use different stage sets and layouts. Configure sales processes, record types, and layout assignments rather than separate Opportunity objects.

**Contextual panel:** A guidance component should appear only for high-risk records. Use Lightning App Builder visibility for presentation, while retaining normal security controls.

## Common mistakes and exam traps

- Rebuilding a standard CRM concept as a custom object without a real gap.
- Choosing master-detail only to obtain a roll-up while ignoring cascade deletion and inherited control.
- Treating record types or component visibility as security.
- Confusing page-layout assignment with Lightning-page activation.
- Expecting a formula to store historical values.
- Using layout-required fields as universal enforcement.
- Creating several objects when one object with genuine process variants is sufficient.
- Changing fields or relationships without dependency and data-impact analysis.

## Final checklist

Can I distinguish an entity from an attribute? Can I choose lookup, master-detail, or junction based on lifecycle? Can I explain roll-up eligibility and cascade deletion? Can I separate record type, business process, page layout, Lightning page, and security? Can I troubleshoot activation and assignment before redesigning? If so, I can answer: **How should the Salesforce data model and user experience be configured for this business requirement?**

## Related topics

Topic 3 decides who can access the configured objects and records. Topic 5 applies standard structures to sales; Topic 6 applies them to service. Topic 8 owns data quality, Topic 9 reporting, and Topic 10 validation and automation.
`,
} as const;

const T = "objects-relationships-lightning-app-builder" as const; const S = "SUPPORTED" as const; const q = (x: Q): Q => x;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_04_QUIZZES: ReadonlyArray<Q> = [
q({id:"SF-PA-T04-Q01",topicSlug:T,objectiveId:"OM-01", blueprintDomain: "objects-app-builder",concept:"Standard versus custom object",difficulty:"easy",type:"conceptual",prompt:"A company wants to track qualified revenue deals with stages and expected close dates. Which starting point best uses Salesforce's native model?",answers:[{id:"A",text:"Create a custom Deal object"},{id:"B",text:"Use the standard Opportunity object"},{id:"C",text:"Store each deal as a Campaign Member"},{id:"D",text:"Create one text field on Account"}],correctAnswerId:"B",explanation:"Opportunity already models revenue deals, stages, and close dates, so it avoids duplicating native behavior. Campaign Members connect people to campaigns, while a text field is not a repeatable deal record. Principle: prefer a fitting standard object. Objective OM-01, Topic 4. Review: Objects and fields.",reviewSection:"Objects and fields",supportStatus:S}),
q({id:"SF-PA-T04-Q02",topicSlug:T,objectiveId:"OM-02", blueprintDomain: "objects-app-builder",concept:"Formula fields",difficulty:"easy",type:"conceptual",prompt:"Which field type displays a value calculated from other fields whenever the record is viewed?",answers:[{id:"A",text:"Formula"},{id:"B",text:"Long Text Area"},{id:"C",text:"Auto Number"},{id:"D",text:"Encrypted Text"}],correctAnswerId:"A",explanation:"A formula derives its displayed value from referenced data and recalculates rather than storing manual input. Text and encrypted fields store entered values; auto number generates identifiers. Principle: formulas are derived values, not historical snapshots. Objective OM-02, Topic 4. Review: Objects and fields.",reviewSection:"Objects and fields",supportStatus:S}),
q({id:"SF-PA-T04-Q03",topicSlug:T,objectiveId:"OM-01", blueprintDomain: "objects-app-builder",concept:"Lookup relationship",difficulty:"easy",type:"configuration-choice",prompt:"A maintenance visit can optionally reference a Facility but must survive if the Facility record is deleted. Which relationship is the better fit?",answers:[{id:"A",text:"Master-detail"},{id:"B",text:"Hierarchical"},{id:"C",text:"Lookup"},{id:"D",text:"Two master-detail fields"}],correctAnswerId:"C",explanation:"Lookup supports a looser association and independent lifecycle, matching an optional visit that must survive its parent. Master-detail creates dependency and cascade deletion; hierarchical is limited to User. Objective OM-01, Topic 4. Review: Relationship decisions.",reviewSection:"Relationship decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q04",topicSlug:T,objectiveId:"OM-03", blueprintDomain: "objects-app-builder",concept:"Record types",difficulty:"easy",type:"conceptual",prompt:"What can record types provide for different groups using the same object?",answers:[{id:"A",text:"Automatic record sharing"},{id:"B",text:"Different processes, picklist subsets, and page-layout assignments"},{id:"C",text:"A replacement for field-level security"},{id:"D",text:"Unlimited object licenses"}],correctAnswerId:"B",explanation:"Record types support process variants, available picklist values, and layout assignment. They do not grant access, replace field security, or change licenses. Principle: record types shape process and experience, not authorization. Objective OM-03, Topic 4. Review: Record types, business processes, and page layouts.",reviewSection:"Record types, business processes, and page layouts",supportStatus:S}),
q({id:"SF-PA-T04-Q05",topicSlug:T,objectiveId:"CS-02", blueprintDomain: "configuration",concept:"Lightning App Builder",difficulty:"easy",type:"conceptual",prompt:"Which tool composes Lightning pages from components for Lightning Experience and the Salesforce mobile app?",answers:[{id:"A",text:"Data Import Wizard"},{id:"B",text:"Schema Builder only"},{id:"C",text:"Sharing Settings"},{id:"D",text:"Lightning App Builder"}],correctAnswerId:"D",explanation:"Lightning App Builder is the point-and-click page composition tool. Schema Builder visualizes and edits the data model, Import Wizard loads data, and Sharing Settings governs record access. Objective CS-02, Topic 4. Review: Lightning App Builder.",reviewSection:"Lightning App Builder",supportStatus:S}),
q({id:"SF-PA-T04-Q06",topicSlug:T,objectiveId:"OM-01", blueprintDomain: "objects-app-builder",concept:"Master-detail lifecycle",difficulty:"medium",type:"short-scenario",prompt:"Invoice Line records must inherit control from Invoice, have no independent lifecycle, and be deleted with the Invoice. Which model best fits?",answers:[{id:"A",text:"A lookup from Invoice to Line"},{id:"B",text:"A master-detail field on Invoice Line"},{id:"C",text:"A text field containing the invoice name"},{id:"D",text:"A hierarchical relationship"}],correctAnswerId:"B",explanation:"The dependent lifecycle, inherited control, and cascade deletion are master-detail characteristics, with the relationship field on the detail. Lookup preserves more independence; text is not relational; hierarchical is User-only. Objective OM-01, Topic 4. Review: Relationship decisions.",reviewSection:"Relationship decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q07",topicSlug:T,objectiveId:"OM-01", blueprintDomain: "objects-app-builder",concept:"Junction object",difficulty:"medium",type:"configuration-choice",prompt:"Consultants can work on many Projects, and each Project can include many Consultants. Hours and role must be stored for each pairing. What should the administrator create?",answers:[{id:"A",text:"A junction object relating Consultant and Project"},{id:"B",text:"Four consultant lookup fields on Project"},{id:"C",text:"A multi-select picklist of projects"},{id:"D",text:"A formula field on Consultant"}],correctAnswerId:"A",explanation:"A junction object models many-to-many associations and stores attributes such as hours and role on each pairing. Repeated lookups impose a fixed count; picklists and formulas do not create relational records. Objective OM-01, Topic 4. Review: Relationship decisions.",reviewSection:"Relationship decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q08",topicSlug:T,objectiveId:"OM-02", blueprintDomain: "objects-app-builder",concept:"Roll-up summary",difficulty:"medium",type:"configuration-choice",prompt:"A custom Invoice must show the sum of Amount across dependent Invoice Lines without custom code. Which design supports a native roll-up summary?",answers:[{id:"A",text:"An unrelated object plus text IDs"},{id:"B",text:"A lookup relationship only"},{id:"C",text:"A master-detail relationship with Invoice as master"},{id:"D",text:"A page layout assignment"}],correctAnswerId:"C",explanation:"A roll-up summary on the master can aggregate supported values from detail records in master-detail. A lookup alone does not provide the native roll-up, while layouts and text identifiers do not aggregate data. Objective OM-02, Topic 4. Review: Relationship decisions.",reviewSection:"Relationship decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q09",topicSlug:T,objectiveId:"OM-02", blueprintDomain: "objects-app-builder",concept:"Field dependencies",difficulty:"medium",type:"administrative-decision",prompt:"The valid Subcategory values should depend on the Category selected by a user. Which declarative configuration is most direct?",answers:[{id:"A",text:"A sharing rule"},{id:"B",text:"A field dependency"},{id:"C",text:"A role hierarchy"},{id:"D",text:"A Lightning page activation"}],correctAnswerId:"B",explanation:"A field dependency limits dependent picklist values based on a controlling field. Sharing and hierarchy affect records, while page activation selects experiences. Principle: use metadata designed for compatible value sets. Objective OM-02, Topic 4. Review: Objects and fields.",reviewSection:"Objects and fields",supportStatus:S}),
q({id:"SF-PA-T04-Q10",topicSlug:T,objectiveId:"OM-03", blueprintDomain: "objects-app-builder",concept:"Page layouts",difficulty:"medium",type:"configuration-choice",prompt:"Two record types need different related lists and record actions on the same object. Which configuration should be assigned by record type and profile?",answers:[{id:"A",text:"Page layouts"},{id:"B",text:"Organization-wide defaults"},{id:"C",text:"Login hours"},{id:"D",text:"Duplicate rules"}],correctAnswerId:"A",explanation:"Page layouts organize details, related lists, buttons, and actions and can be assigned by record type and profile. OWD controls record access; login hours and duplicate rules solve different concerns. Objective OM-03, Topic 4. Review: Record types, business processes, and page layouts.",reviewSection:"Record types, business processes, and page layouts",supportStatus:S}),
q({id:"SF-PA-T04-Q11",topicSlug:T,objectiveId:"CS-02", blueprintDomain: "configuration",concept:"Lightning page activation",difficulty:"medium",type:"troubleshooting",prompt:"A custom Account record page appears for Sales users but not Service users in another app. What should the administrator inspect first?",answers:[{id:"A",text:"Corporate currency"},{id:"B",text:"Account ownership transfer"},{id:"C",text:"Lightning page activation and app/profile assignment"},{id:"D",text:"Password policies"}],correctAnswerId:"C",explanation:"Different experiences by app or persona commonly point to Lightning record-page activation and assignment. Currency, ownership, and passwords cannot select a page. Principle: diagnose page targeting before rebuilding UI. Objective CS-02, Topic 4. Review: Troubleshooting the model and UI.",reviewSection:"Troubleshooting the model and UI",supportStatus:S}),
q({id:"SF-PA-T04-Q12",topicSlug:T,objectiveId:"OM-03", blueprintDomain: "objects-app-builder",concept:"Component visibility",difficulty:"medium",type:"short-scenario",prompt:"A guidance component should appear only when Risk Level is High, but all authorized users retain normal record access. What is the best UI configuration?",answers:[{id:"A",text:"Set every record to Private"},{id:"B",text:"Use component visibility on the Lightning page"},{id:"C",text:"Create a new user license"},{id:"D",text:"Delete the component for other records"}],correctAnswerId:"B",explanation:"Component visibility conditionally presents guidance based on record context without changing authorization. OWD and licenses affect access, and deletion removes the component universally. Remember that visibility rules are presentation, not security. Objective OM-03, Topic 4. Review: Lightning App Builder.",reviewSection:"Lightning App Builder",supportStatus:S}),
q({id:"SF-PA-T04-Q13",topicSlug:T,objectiveId:"OM-03", blueprintDomain: "objects-app-builder",concept:"Layout requiredness",difficulty:"medium",type:"best-practice",prompt:"A field must be populated for records created through UI, API, imports, and automation. Why is marking it required only on a page layout insufficient?",answers:[{id:"A",text:"Page-layout requiredness is an interface behavior, not universal enforcement"},{id:"B",text:"Page layouts always delete imported values"},{id:"C",text:"Required fields cannot appear in reports"},{id:"D",text:"Record types disable every required field"}],correctAnswerId:"A",explanation:"Layout-required settings govern that interface and can be bypassed by other save paths. Universal data integrity needs an appropriate schema or validation control, owned later in Topic 10. The other claims are false. Objective OM-03, Topic 4. Review: Record types, business processes, and page layouts.",reviewSection:"Record types, business processes, and page layouts",supportStatus:S}),
q({id:"SF-PA-T04-Q14",topicSlug:T,objectiveId:"CS-02", blueprintDomain: "configuration",concept:"App navigation",difficulty:"medium",type:"troubleshooting",prompt:"Users have object permission but cannot find the custom object in one Lightning app's navigation. Which configuration is the most targeted check?",answers:[{id:"A",text:"Fiscal year"},{id:"B",text:"Case escalation rule"},{id:"C",text:"Role hierarchy"},{id:"D",text:"The app's navigation items and tab visibility"}],correctAnswerId:"D",explanation:"With permission established, inspect whether the object tab is included and visible in that app's navigation. Fiscal year, case escalation, and hierarchy do not configure navigation. Objective CS-02, Topic 4. Review: Declarative user-experience decisions.",reviewSection:"Declarative user-experience decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q15",topicSlug:T,objectiveId:"OM-02", blueprintDomain: "objects-app-builder",concept:"Field deletion impact",difficulty:"medium",type:"administrative-decision",prompt:"A custom field appears unused and is proposed for deletion. What should the administrator do before removing it?",answers:[{id:"A",text:"Delete it immediately because layouts preserve the data"},{id:"B",text:"Inspect data and references in formulas, reports, integrations, layouts, and automation"},{id:"C",text:"Change all record owners"},{id:"D",text:"Disable MFA"}],correctAnswerId:"B",explanation:"Schema deletion can affect stored data and dependent metadata or integrations, so dependency and data-impact analysis comes first. Layouts do not preserve deleted data; ownership and MFA are unrelated. Objective OM-02, Topic 4. Review: Troubleshooting the model and UI.",reviewSection:"Troubleshooting the model and UI",supportStatus:S}),
q({id:"SF-PA-T04-Q16",topicSlug:T,objectiveId:"OM-03", blueprintDomain: "objects-app-builder",concept:"Business process",difficulty:"medium",type:"troubleshooting",prompt:"Retail Opportunity users see enterprise-only stage values despite having the intended page layout. Which configuration chain should be reviewed?",answers:[{id:"A",text:"User locale and time zone"},{id:"B",text:"OWD and sharing rules"},{id:"C",text:"Opportunity record type and its associated sales process"},{id:"D",text:"Trusted IP ranges"}],correctAnswerId:"C",explanation:"Opportunity stage availability is governed through the sales process associated with the record type; a page layout alone does not define the stage set. Sharing and login settings are unrelated. Objective OM-03, Topic 4. Review: Record types, business processes, and page layouts.",reviewSection:"Record types, business processes, and page layouts",supportStatus:S}),
q({id:"SF-PA-T04-Q17",topicSlug:T,objectiveId:"OM-01", blueprintDomain: "objects-app-builder",concept:"Relationship conversion",difficulty:"hard",type:"administrative-decision",prompt:"An administrator wants to convert an existing lookup to master-detail to enable roll-ups. Which analysis is most important before the change?",answers:[{id:"A",text:"Whether Campaign Members have statuses"},{id:"B",text:"Whether users prefer a different app color"},{id:"C",text:"Whether the fiscal year is standard"},{id:"D",text:"Whether every child can meet required parent and dependency constraints, including ownership and deletion effects"}],correctAnswerId:"D",explanation:"Conversion changes lifecycle and control, and existing orphaned or incompatible records can block it. Roll-ups alone do not justify ignoring required parent, ownership, sharing, and cascade-delete implications. Objective OM-01, Topic 4. Review: Relationship decisions.",reviewSection:"Relationship decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q18",topicSlug:T,objectiveId:"OM-01", blueprintDomain: "objects-app-builder",concept:"Data-model choice",difficulty:"hard",type:"short-scenario",prompt:"Regional permits belong to Facilities today, but legal retention requires permits to remain independently owned after a Facility is removed. Managers also want totals by Facility. What is the safest core relationship choice?",answers:[{id:"A",text:"Master-detail solely for native roll-ups"},{id:"B",text:"Lookup for independent lifecycle, then evaluate an appropriate aggregate solution separately"},{id:"C",text:"Store permit IDs in a multi-select picklist"},{id:"D",text:"Use a hierarchical User relationship"}],correctAnswerId:"B",explanation:"Legal retention and independent ownership outweigh convenience of native master-detail roll-ups. Lookup preserves independence; aggregation can be solved separately in its proper scope. Picklists and User hierarchy misrepresent the entity relationship. Objective OM-01, Topic 4. Review: Relationship decisions.",reviewSection:"Relationship decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q19",topicSlug:T,objectiveId:"OM-03", blueprintDomain: "objects-app-builder",concept:"Record type versus object",difficulty:"hard",type:"best-practice",prompt:"Two divisions sell the same kind of Opportunity but use different stage sets, picklist values, and layouts. Which design avoids unnecessary data fragmentation?",answers:[{id:"A",text:"Create two unrelated custom deal objects"},{id:"B",text:"Store stages in free text"},{id:"C",text:"Use profiles as the only process control"},{id:"D",text:"Use Opportunity sales processes, record types, and assigned layouts"}],correctAnswerId:"D",explanation:"The entity remains Opportunity, while record types connect distinct sales processes, values, and layouts. Separate objects fragment native sales behavior; text weakens control; profiles alone do not define process variants. Objective OM-03, Topic 4. Review: Declarative user-experience decisions.",reviewSection:"Declarative user-experience decisions",supportStatus:S}),
q({id:"SF-PA-T04-Q20",topicSlug:T,objectiveId:"CS-02", blueprintDomain: "configuration",concept:"UI versus security",difficulty:"hard",type:"short-scenario",prompt:"A confidential field is hidden with Lightning component visibility, but a user can still retrieve it elsewhere. What is the correct remediation?",answers:[{id:"A",text:"Add another visibility filter only"},{id:"B",text:"Remove the field from one list view"},{id:"C",text:"Configure appropriate field-level security, then use visibility for presentation"},{id:"D",text:"Change the user's time zone"}],correctAnswerId:"C",explanation:"Component visibility is a user-experience rule, not an authorization boundary. Field-level security must restrict the field across access paths; UI visibility can then tailor presentation. List views and time zones do not secure data. Objective CS-02 boundary, Topic 4. Review: Lightning App Builder.",reviewSection:"Lightning App Builder",supportStatus:S}),
q({id:"SF-PA-T04-Q21",topicSlug:T,objectiveId:"OM-02", blueprintDomain: "objects-app-builder",concept:"Formula snapshot boundary",difficulty:"hard",type:"configuration-choice",prompt:"A contract must preserve the exchange rate used at approval even if the current rate later changes. Why is a formula referencing today's rate a poor design?",answers:[{id:"A",text:"Formula fields cannot display numbers"},{id:"B",text:"A formula recalculates and does not preserve a historical snapshot"},{id:"C",text:"Formula fields automatically create child records"},{id:"D",text:"Formulas change organization-wide defaults"}],correctAnswerId:"B",explanation:"A formula derives the current result from referenced values, so it does not freeze the approval-time rate. A stored value populated by an appropriate process is needed in the later automation scope. The other statements misdescribe formulas. Objective OM-02, Topic 4. Review: Objects and fields.",reviewSection:"Objects and fields",supportStatus:S}),
q({id:"SF-PA-T04-Q22",topicSlug:T,objectiveId:"CS-02", blueprintDomain: "configuration",concept:"Layered UI troubleshooting",difficulty:"hard",type:"troubleshooting",prompt:"One persona sees the correct object but the wrong fields, actions, and side-panel components on a record. What sequence best isolates the configuration?",answers:[{id:"A",text:"Reset every user's password"},{id:"B",text:"Immediately make OWD public"},{id:"C",text:"Recreate the object and migrate all records"},{id:"D",text:"Inspect record type and page-layout assignment, then Lightning-page activation and component visibility, then security if data remains missing"}],correctAnswerId:"D",explanation:"The symptoms span layout and Lightning composition, so inspect each assignment layer in order and cross to security only for access gaps. Public sharing, object recreation, and password resets are broad and unrelated. Objective CS-02, Topic 4. Review: Troubleshooting the model and UI.",reviewSection:"Troubleshooting the model and UI",supportStatus:S}),
];
