import type { SalesforceEditorialQuestion } from "./salesforce-editorial-types";
type Q = SalesforceEditorialQuestion<"sales-marketing", "SM-01" | "SM-02" | "SM-03">;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_05_SOURCES = [
  { title:"Salesforce Certified Platform Administrator Exam Guide",url:"https://help.salesforce.com/s/articleView?id=005298966&type=1&language=en_US",lastVerifiedAt:"2026-08-20",objectiveIds:["SM-01","SM-02","SM-03"] },
  { title:"Convert and Assign Leads",url:"https://trailhead.salesforce.com/content/learn/modules/leads_opportunities_lightning_experience/convert-and-assign-leads",lastVerifiedAt:"2026-08-20",objectiveIds:["SM-01","SM-03"] },
  { title:"Opportunities and Products",url:"https://trailhead.salesforce.com/content/learn/modules/opportunity-management",lastVerifiedAt:"2026-08-20",objectiveIds:["SM-01","SM-02"] },
  { title:"Campaign Basics",url:"https://trailhead.salesforce.com/content/learn/modules/campaign_basics",lastVerifiedAt:"2026-08-20",objectiveIds:["SM-03"] },
] as const;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_05_REVIEW={id:"SF-PA-T05-REVIEW-EN",language:"en",topicSlug:"sales-marketing",title:"Sales and Marketing Applications — Exam Review",objectiveIds:["SM-01","SM-02","SM-03"],blueprintDomains:["Sales and Marketing Applications"],lastVerifiedAt:"2026-08-20",sourceUrls:SALESFORCE_PLATFORM_ADMIN_TOPIC_05_SOURCES.map(s=>s.url),content:`## Learning objectives

This review explains how Salesforce supports the path from prospect to revenue and how an administrator selects configuration for a business requirement. Topic 5 owns **SM-01**, **SM-02**, and **SM-03**. Topic 4 owns generic object and UI mechanics; Topic 10 owns general-purpose Flow and approval design. Here, those capabilities appear only as context for the sales process.

## Sales data model

A Lead represents an unqualified prospect whose fit or interest is not yet established. An Account represents a company or, when the org uses the relevant model, a person account. A Contact is a person related to an account. An Opportunity represents a potential revenue transaction associated with an account. Do not use Leads for existing customers merely because a new inquiry arrived; decide whether the person is genuinely an unqualified prospect or already belongs in the account/contact model.

Products represent items or services sold. A price book supplies product prices for a selling context. The standard price book establishes standard prices; custom price books can offer different prices or subsets for markets or customer segments. Opportunity products connect priced products to an opportunity. A product being active does not by itself make it selectable everywhere: price-book and price-book-entry configuration matters.

## Lead qualification, assignment, and conversion

Lead status tracks progress before conversion. Lead assignment rules route eligible new leads to a user or queue according to ordered criteria. Assignment is not qualification and does not convert a lead. Web-to-Lead can capture submissions as leads, while duplicate controls and data-quality decisions belong primarily to Topic 8.

Conversion changes the prospect into the core sales model. Salesforce creates or associates an Account and Contact, and can create an Opportunity depending on the conversion choice and configuration. Lead field mappings determine how supported custom lead fields transfer to target fields. The converted lead becomes historical; sellers continue on the resulting account, contact, and optional opportunity. Before changing mappings, confirm compatible target field types and business ownership of the data.

When duplicates exist, use the matching Account or Contact during conversion where appropriate rather than blindly creating another customer record. Conversion is not a substitute for complete qualification criteria. It is the transition once the business determines the prospect should enter the customer and opportunity process.

## Opportunities, stages, and sales processes

Opportunity stage communicates where a deal is in its lifecycle and is associated with probability and forecast category behavior. Administrators should align stages to meaningful seller actions and exit criteria, not create numerous subjective labels. A sales process selects the stage values available for an opportunity record type. Record types can then support distinct sales motions, picklist subsets, and layouts. Page layouts alone do not define the available stage set.

Path can present key fields and guidance for success at stages or statuses. It guides users; it does not replace sound stage definitions, validation, or automation. Troubleshoot an unexpected stage list by checking the record type and associated sales process before altering global values.

Products and price books support line-level deal detail. Select the correct price book before adding opportunity products. If users cannot add a product, check product activation, price-book activation, a relevant active price-book entry, currency compatibility in multi-currency contexts, and user access before inventing a new product.

## Campaigns and campaign members

A Campaign represents a marketing initiative. Campaign Members connect Leads and Contacts to the campaign. Member statuses describe responses appropriate to that campaign and one status can be designated as responded. Campaign membership does not replace the Lead or Contact record and does not by itself create an Opportunity.

Use campaign hierarchies to organize related initiatives for aggregate understanding. Keep member statuses consistent enough for meaningful measurement while allowing campaign-type needs. If response reporting is wrong, inspect member status configuration and the Responded designation, not opportunity stages.

Campaign influence connects marketing activity to opportunities under configured models, but avoid assuming every member automatically proves causation. The administrator configures a model and reliable associations; the business interprets attribution.

## Sales productivity and forecasting

Activities—tasks and events—record planned or completed work with prospects and customers. List views, Kanban, Path, email features, and other productivity tools help sellers act on records, but each solves a distinct problem. Forecasting summarizes expected sales using configured forecast types, categories, hierarchy, and eligible data. Territory management organizes account access and sales responsibility by territory; it is not a replacement for opportunity stages or lead assignment.

Choose the feature that matches the requirement. Guidance at a stage suggests Path. Different allowable stages suggest sales processes and record types. Routing new prospects suggests lead assignment rules. A different catalog or price schedule suggests a custom price book. Marketing participation suggests Campaign Members. Management projections suggest forecasting, with reports and dashboards treated in Topic 9.

## Troubleshooting sales configuration

Follow the record lifecycle. For lead routing, confirm the active assignment rule, entry order, criteria, and whether the creation path invoked it. For conversion, inspect required data, custom field mappings, duplicate candidates, and target choices. For stage availability, inspect record type and sales process. For missing products, inspect the full product–price book–entry chain. For campaign reporting, inspect membership and status semantics.

Avoid broad permission changes until configuration and access evidence identify the layer. A seller who cannot see any Opportunities may have an access issue from Topic 3; a seller who sees the opportunity but lacks an expected stage probably has a process configuration issue in this topic.

## Mini-scenarios

**New inquiry:** A previously unknown visitor submits a form and requires qualification. Create and route a Lead.

**Qualified prospect:** The business accepts the prospect. Convert to an existing or new Account and Contact and create an Opportunity when an active deal exists.

**Distinct selling motions:** Direct and partner deals use different allowed stages. Use sales processes connected to record types, then assign suitable layouts.

**Regional pricing:** The same products need market-specific prices. Use an appropriate custom price book rather than duplicating opportunity fields.

**Webinar response:** Add Leads and Contacts as Campaign Members and use meaningful member statuses, including the correct responded designation.

## Common mistakes and exam traps

- Treating lead assignment as lead conversion.
- Creating duplicate Accounts and Contacts during conversion without checking matches.
- Assuming conversion must always create a new Opportunity.
- Using page layouts to control stage availability instead of the sales process.
- Confusing Campaign Members with Opportunities or customers.
- Activating a Product but omitting its usable price-book entry.
- Selecting forecasting when the need is transactional routing.
- Creating many vague stages that do not represent buyer or seller progress.

## Final checklist

Can I trace **Lead → Qualification → Conversion → Account/Contact/Opportunity → Sales process**? Can I choose between assignment, conversion, Path, record types, price books, campaigns, territories, and forecasting? Can I troubleshoot the relevant configuration chain without drifting into generic sales advice? If so, I can make administrator-level sales decisions.

## Related topics

Topic 4 defines generic record types, layouts, objects, and relationships. Topic 3 governs access. Topic 8 owns duplicate prevention, Topic 9 analytics, and Topic 10 general automation.
`} as const;
const T="sales-marketing" as const,S="SUPPORTED" as const,q=(x:Q):Q=>x;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_05_QUIZZES:ReadonlyArray<Q>=[
q({id:"SF-PA-T05-Q01",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Lead purpose",difficulty:"easy",type:"conceptual",prompt:"Which record normally represents a prospect who has not yet been qualified?",answers:[{id:"A",text:"Case"},{id:"B",text:"Lead"},{id:"C",text:"Campaign"},{id:"D",text:"Price Book"}],correctAnswerId:"B",explanation:"A Lead holds an unqualified prospect before transition to the account/contact/opportunity model. Cases track support, Campaigns marketing initiatives, and Price Books pricing. Principle: choose the object that matches lifecycle. Objective SM-01, Topic 5. Review: Sales data model.",reviewSection:"Sales data model",supportStatus:S}),
q({id:"SF-PA-T05-Q02",topicSlug:T,objectiveId:"SM-03", blueprintDomain: "sales-marketing",concept:"Campaign members",difficulty:"easy",type:"conceptual",prompt:"What does a Campaign Member connect to a marketing campaign?",answers:[{id:"A",text:"A Lead or Contact"},{id:"B",text:"Only a Product"},{id:"C",text:"Only a Case"},{id:"D",text:"A fiscal year"}],correctAnswerId:"A",explanation:"Campaign Members associate Leads or Contacts with a marketing initiative and carry response status. Products, Cases, and fiscal years do not represent campaign participation. Objective SM-03, Topic 5. Review: Campaigns and campaign members.",reviewSection:"Campaigns and campaign members",supportStatus:S}),
q({id:"SF-PA-T05-Q03",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Opportunity",difficulty:"easy",type:"conceptual",prompt:"Which standard object represents a potential revenue transaction with an expected close date?",answers:[{id:"A",text:"Contact"},{id:"B",text:"Task"},{id:"C",text:"Opportunity"},{id:"D",text:"Queue"}],correctAnswerId:"C",explanation:"Opportunity models a potential revenue deal, including stage and close-date information. Contacts are people, Tasks are activities, and Queues hold work. Objective SM-01, Topic 5. Review: Sales data model.",reviewSection:"Sales data model",supportStatus:S}),
q({id:"SF-PA-T05-Q04",topicSlug:T,objectiveId:"SM-03", blueprintDomain: "sales-marketing",concept:"Lead assignment",difficulty:"easy",type:"conceptual",prompt:"Which feature routes eligible new Leads to users or queues using ordered criteria?",answers:[{id:"A",text:"Escalation rules"},{id:"B",text:"Sales processes"},{id:"C",text:"Forecast categories"},{id:"D",text:"Lead assignment rules"}],correctAnswerId:"D",explanation:"Lead assignment rules evaluate ordered entries to route eligible leads. Escalation is for Cases, sales processes select Opportunity stages, and forecast categories summarize pipeline. Objective SM-03, Topic 5. Review: Lead qualification, assignment, and conversion.",reviewSection:"Lead qualification, assignment, and conversion",supportStatus:S}),
q({id:"SF-PA-T05-Q05",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Lead conversion",difficulty:"medium",type:"short-scenario",prompt:"A qualified lead belongs to an existing customer and represents a new deal. What is the best conversion choice?",answers:[{id:"A",text:"Associate the existing Account, create or match the Contact, and create an Opportunity"},{id:"B",text:"Create a duplicate Account every time"},{id:"C",text:"Convert the lead into a Case"},{id:"D",text:"Keep the lead indefinitely and add opportunity stages to it"}],correctAnswerId:"A",explanation:"Conversion can associate an existing Account, create or match a Contact, and create an Opportunity for the active deal. Duplicating customers harms quality; Cases and Lead stages do not replace the sales model. Objective SM-01, Topic 5. Review: Lead qualification, assignment, and conversion.",reviewSection:"Lead qualification, assignment, and conversion",supportStatus:S}),
q({id:"SF-PA-T05-Q06",topicSlug:T,objectiveId:"SM-03", blueprintDomain: "sales-marketing",concept:"Lead field mapping",difficulty:"medium",type:"configuration-choice",prompt:"A custom qualification value must transfer from Lead to the resulting Contact during conversion. What should the administrator configure?",answers:[{id:"A",text:"Lead custom field mapping to a compatible Contact field"},{id:"B",text:"Case escalation hours"},{id:"C",text:"Dashboard folder sharing"},{id:"D",text:"A Campaign hierarchy"}],correctAnswerId:"A",explanation:"Lead field mapping carries supported custom values into compatible target fields during conversion. Escalation, dashboard folders, and campaign hierarchy do not map conversion data. Objective SM-03, Topic 5. Review: Lead qualification, assignment, and conversion.",reviewSection:"Lead qualification, assignment, and conversion",supportStatus:S}),
q({id:"SF-PA-T05-Q07",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Sales process",difficulty:"medium",type:"configuration-choice",prompt:"Two Opportunity record types require different allowed stage sets. Which configuration provides those stage subsets?",answers:[{id:"A",text:"Two login-hour schedules"},{id:"B",text:"Two sharing rules"},{id:"C",text:"Sales processes associated with the record types"},{id:"D",text:"Campaign member statuses"}],correctAnswerId:"C",explanation:"A sales process selects Opportunity stages and is associated through a record type. Login hours and sharing govern access; Campaign Member statuses describe marketing response. Objective SM-01, Topic 5. Review: Opportunities, stages, and sales processes.",reviewSection:"Opportunities, stages, and sales processes",supportStatus:S}),
q({id:"SF-PA-T05-Q08",topicSlug:T,objectiveId:"SM-02", blueprintDomain: "sales-marketing",concept:"Path",difficulty:"medium",type:"administrative-decision",prompt:"Sales representatives need key fields and guidance displayed for each Opportunity stage. Which feature most directly fits?",answers:[{id:"A",text:"Path"},{id:"B",text:"Organization-wide defaults"},{id:"C",text:"Data Export"},{id:"D",text:"Case queues"}],correctAnswerId:"A",explanation:"Path presents key fields and guidance at stages, supporting seller execution. OWD controls record access, Data Export extracts data, and Case queues route service work. Path guides the process but does not replace stage configuration. Objective SM-02, Topic 5. Review: Opportunities, stages, and sales processes.",reviewSection:"Opportunities, stages, and sales processes",supportStatus:S}),
q({id:"SF-PA-T05-Q09",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Price books",difficulty:"medium",type:"short-scenario",prompt:"The same active products need different approved prices for public-sector customers. What should the administrator configure?",answers:[{id:"A",text:"Duplicate every Account"},{id:"B",text:"A custom price book with the applicable product entries"},{id:"C",text:"A new Opportunity stage for each price"},{id:"D",text:"A Case assignment rule"}],correctAnswerId:"B",explanation:"A custom price book supports a distinct price schedule and relevant product entries. Duplicating Accounts or stages misuses the model, and Case assignment is unrelated. Objective SM-01, Topic 5. Review: Sales data model.",reviewSection:"Sales data model",supportStatus:S}),
q({id:"SF-PA-T05-Q10",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Product availability",difficulty:"medium",type:"troubleshooting",prompt:"An active Product cannot be added to an Opportunity using a selected price book. What should be checked next?",answers:[{id:"A",text:"The user's MFA method"},{id:"B",text:"Case business hours"},{id:"C",text:"The active price book and applicable active price-book entry"},{id:"D",text:"Campaign hierarchy"}],correctAnswerId:"C",explanation:"Opportunity product selection depends on the selected price book and a usable price-book entry, not merely Product activation. MFA, service hours, and campaign hierarchy do not supply product pricing. Objective SM-01, Topic 5. Review: Opportunities, stages, and sales processes.",reviewSection:"Opportunities, stages, and sales processes",supportStatus:S}),
q({id:"SF-PA-T05-Q11",topicSlug:T,objectiveId:"SM-03", blueprintDomain: "sales-marketing",concept:"Campaign response",difficulty:"medium",type:"troubleshooting",prompt:"Webinar attendance is not counted as campaign response even though members have an Attended status. What should the administrator inspect?",answers:[{id:"A",text:"Whether the Attended member status is designated Responded"},{id:"B",text:"Opportunity forecast categories"},{id:"C",text:"Profile login IP ranges"},{id:"D",text:"Case escalation age"}],correctAnswerId:"A",explanation:"Campaign response measurement depends on Campaign Member status configuration, including which status is marked Responded. Forecasting, login restrictions, and case escalation do not determine marketing response. Objective SM-03, Topic 5. Review: Campaigns and campaign members.",reviewSection:"Campaigns and campaign members",supportStatus:S}),
q({id:"SF-PA-T05-Q12",topicSlug:T,objectiveId:"SM-02", blueprintDomain: "sales-marketing",concept:"Forecasting",difficulty:"medium",type:"configuration-choice",prompt:"Sales leadership wants a structured projection of expected revenue using pipeline categories and a forecast hierarchy. Which capability fits?",answers:[{id:"A",text:"Web-to-Case"},{id:"B",text:"Duplicate Rules"},{id:"C",text:"Lightning page visibility"},{id:"D",text:"Collaborative Forecasts"}],correctAnswerId:"D",explanation:"Collaborative Forecasts summarizes eligible pipeline through configured forecast types, categories, and hierarchy. Web-to-Case creates support work; duplicate rules and component visibility solve different problems. Objective SM-02, Topic 5. Review: Sales productivity and forecasting.",reviewSection:"Sales productivity and forecasting",supportStatus:S}),
q({id:"SF-PA-T05-Q13",topicSlug:T,objectiveId:"SM-03", blueprintDomain: "sales-marketing",concept:"Assignment rule troubleshooting",difficulty:"medium",type:"troubleshooting",prompt:"Imported Leads all remain with the importing user although an active assignment rule exists. What is the best first investigation?",answers:[{id:"A",text:"Make every Lead public"},{id:"B",text:"Confirm the import path invoked the active rule and inspect rule order and criteria"},{id:"C",text:"Change the Opportunity sales process"},{id:"D",text:"Delete the Lead record type"}],correctAnswerId:"B",explanation:"An active rule only helps when the creation path invokes it and a rule entry matches in order. Public sharing changes visibility, while Opportunity processes and deleting record types do not diagnose routing. Objective SM-03, Topic 5. Review: Troubleshooting sales configuration.",reviewSection:"Troubleshooting sales configuration",supportStatus:S}),
q({id:"SF-PA-T05-Q14",topicSlug:T,objectiveId:"SM-02", blueprintDomain: "sales-marketing",concept:"Territory management",difficulty:"medium",type:"conceptual",prompt:"Which requirement is most closely aligned with Enterprise Territory Management?",answers:[{id:"A",text:"Restricting login by network"},{id:"B",text:"Calculating case escalation time"},{id:"C",text:"Organizing account access and sales responsibility by territory"},{id:"D",text:"Defining dependent picklists"}],correctAnswerId:"C",explanation:"Territory management models sales responsibility and account access using territory structures. Network restrictions, service escalation, and field dependencies are separate administrative concerns. Objective SM-02, Topic 5. Review: Sales productivity and forecasting.",reviewSection:"Sales productivity and forecasting",supportStatus:S}),
q({id:"SF-PA-T05-Q15",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Conversion choice",difficulty:"hard",type:"short-scenario",prompt:"A qualified prospect is a known Contact at an existing Account, but no active purchase is being discussed. Which conversion outcome avoids false pipeline?",answers:[{id:"A",text:"Assign the Lead to an escalation queue"},{id:"B",text:"Create a duplicate Account and mandatory Opportunity"},{id:"C",text:"Create a Case instead of converting"},{id:"D",text:"Match the existing customer records and convert without creating an Opportunity"}],correctAnswerId:"D",explanation:"Conversion can associate the existing customer and omit Opportunity creation when no deal exists, preserving pipeline quality. Forced duplicates and false opportunities distort data; Cases and escalation queues serve support. Objective SM-01, Topic 5. Review: Lead qualification, assignment, and conversion.",reviewSection:"Lead qualification, assignment, and conversion",supportStatus:S}),
q({id:"SF-PA-T05-Q16",topicSlug:T,objectiveId:"SM-03", blueprintDomain: "sales-marketing",concept:"Campaign attribution boundary",difficulty:"hard",type:"best-practice",prompt:"Marketing wants every Campaign Member automatically treated as proof that the campaign caused every later Opportunity. What is the best administrative response?",answers:[{id:"A",text:"Replace Contacts with Campaigns"},{id:"B",text:"Create one Opportunity stage per campaign"},{id:"C",text:"Delete nonresponding members"},{id:"D",text:"Configure reliable membership and an appropriate influence model, while distinguishing association from causation"}],correctAnswerId:"D",explanation:"Campaign influence depends on configured models and trustworthy associations; membership alone does not prove causation. Replacing objects, multiplying stages, or deleting valid history corrupts the model. Objective SM-03, Topic 5. Review: Campaigns and campaign members.",reviewSection:"Campaigns and campaign members",supportStatus:S}),
q({id:"SF-PA-T05-Q17",topicSlug:T,objectiveId:"SM-01", blueprintDomain: "sales-marketing",concept:"Stage troubleshooting",difficulty:"hard",type:"troubleshooting",prompt:"Partner sellers see the intended layout but cannot select stages that direct sellers use. What should be checked before editing the global Stage field?",answers:[{id:"A",text:"Campaign response status"},{id:"B",text:"The partner Opportunity record type and associated sales process"},{id:"C",text:"Organization trusted IPs"},{id:"D",text:"Case auto-response rules"}],correctAnswerId:"B",explanation:"Allowed Opportunity stages come from the sales process associated with the record type; layout correctness does not prove process correctness. Campaign, login, and service settings are irrelevant. Objective SM-01, Topic 5. Review: Troubleshooting sales configuration.",reviewSection:"Troubleshooting sales configuration",supportStatus:S}),
q({id:"SF-PA-T05-Q18",topicSlug:T,objectiveId:"SM-02", blueprintDomain: "sales-marketing",concept:"Feature selection",difficulty:"hard",type:"administrative-decision",prompt:"A company needs prospect routing, stage-specific seller guidance, and quarterly management projections. Which combination addresses each requirement without substituting analytics for transactions?",answers:[{id:"A",text:"Forecasts for routing, Cases for guidance, and Leads for projections"},{id:"B",text:"Campaigns for all three requirements"},{id:"C",text:"Lead assignment rules, Path, and Collaborative Forecasts respectively"},{id:"D",text:"One custom text field for all three"}],correctAnswerId:"C",explanation:"Lead assignment routes prospects, Path guides stage work, and Collaborative Forecasts projects pipeline. Each purpose-built feature matches one requirement; using one unrelated feature for all creates semantic and operational gaps. Objective SM-02 with SM-03 context, Topic 5. Review: Sales productivity and forecasting.",reviewSection:"Sales productivity and forecasting",supportStatus:S}),
];
