import type { SalesforceEditorialQuestion } from "./salesforce-editorial-types";
type Q=SalesforceEditorialQuestion<"service-support","SS-01"|"SS-02">;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_06_SOURCES=[
{title:"Salesforce Certified Platform Administrator Exam Guide",url:"https://help.salesforce.com/s/articleView?id=005298966&type=1&language=en_US",lastVerifiedAt:"2026-08-20",objectiveIds:["SS-01","SS-02"]},
{title:"Service Cloud for Lightning Experience",url:"https://trailhead.salesforce.com/content/learn/modules/service_lex",lastVerifiedAt:"2026-08-20",objectiveIds:["SS-01","SS-02"]},
{title:"Enhance Customer Service with Automated Case Management",url:"https://trailhead.salesforce.com/en/content/learn/modules/service_lex/service_lex_case_manage",lastVerifiedAt:"2026-08-20",objectiveIds:["SS-01","SS-02"]},
{title:"Create a Case Escalation Rule",url:"https://trailhead.salesforce.com/content/learn/projects/set-up-case-escalation-entitlements/create-case-escalation-rule",lastVerifiedAt:"2026-08-20",objectiveIds:["SS-02"]},
] as const;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_06_REVIEW={id:"SF-PA-T06-REVIEW-EN",language:"en",topicSlug:"service-support",title:"Service and Support Applications — Exam Review",objectiveIds:["SS-01","SS-02"],blueprintDomains:["Service and Support Applications"],lastVerifiedAt:"2026-08-20",sourceUrls:SALESFORCE_PLATFORM_ADMIN_TOPIC_06_SOURCES.map(s=>s.url),content:`## Learning objectives

This review prepares you to configure how Salesforce receives, routes, manages, escalates, and resolves customer support work. Topic 6 owns **SS-01** and **SS-02**. Topic 4 owns generic page and data-model mechanics; Topic 10 owns general Flow design. Advanced entitlement implementation is not a primary focus here, although business hours and milestones are identified at their administrator-level boundary.

## Cases and the support lifecycle

A Case represents a customer issue, request, or support interaction that must be tracked to resolution. Typical lifecycle data includes origin, type, reason, priority, status, owner, account, and contact. Status should communicate meaningful progress, while a support process determines which Case status values are available for a record type. Record types and layouts can support distinct service motions, such as product support and billing inquiries.

Case ownership can belong to a user or a queue. A queue holds unassigned or pooled work for its members to take or manage. Queue ownership is useful when a team, rather than one named agent, should receive incoming work. It is not itself a time-based escalation mechanism.

## Case intake and responses

Web-to-Case captures customer submissions from a website into Cases. Email-to-Case converts supported inbound email into Cases and supports an email-based service channel. Configure routing addresses, defaults, and security or processing choices appropriate to the org. These intake mechanisms create service records; they do not replace assignment, escalation, access control, or a complete customer portal.

Case auto-response rules send an initial email response based on ordered criteria, using an email template and sender configuration. They acknowledge or tailor communication; they do not determine ongoing ownership. A default response can cover cases that do not match a specialized entry when configured appropriately.

Distinguish the moments: intake creates the Case, assignment chooses its initial owner, auto-response communicates with the customer, escalation reacts when service thresholds are missed, and closure records the resolution.

## Queues and assignment rules

Case assignment rules use ordered entries and criteria to assign Cases to users or queues. Only one Case assignment rule can be active at a time, but it can contain multiple entries. Entry order matters because the first matching entry determines the assignment. The record-creation path must invoke the active assignment rule; an active rule is not proof that every integration or manual save used it.

Use a queue when a pool of agents should share work. Define supported objects, queue members, and routing expectations. If cases remain in a queue, determine whether membership, list visibility, operating procedure, or another routing capability is missing before assuming the assignment rule failed. Assignment answers **who should own this case now?**

Troubleshoot routing by checking the active rule, entry order, criteria, case field values at evaluation time, invocation by the intake path, and the target user or queue. Avoid making all Cases public as a shortcut; access and assignment are distinct.

## Escalation, business hours, and service targets

Escalation rules perform time-based actions when Cases meet criteria and remain unresolved according to configured timing. Actions can reassign a Case and notify users. Only one escalation rule can be active, with ordered entries and escalation actions. Escalation answers **what should happen when this case has waited too long?** It is different from initial assignment.

Business hours define when a support team operates and can be used in service timing. Holidays can exclude nonworking dates from relevant calculations. They do not restrict when users can log in; profile login hours belong to Topic 2. Select the business-hours context that matches the service commitment rather than counting every clock hour.

Entitlements can represent a customer's support eligibility, and milestones can track required steps or response targets in an entitlement process. For this topic, recognize when a contractual service target needs entitlement and milestone capabilities, but do not assume every simple aging requirement requires a full entitlement implementation. A straightforward time-based reassignment may be addressed by an escalation rule.

## Service Console and Knowledge

The Service Console is a workspace designed for agents to manage service records efficiently, often with tabbed navigation, utility tools, and contextual components. Configure the app and record experience for the support workflow. A console improves productivity; it does not grant missing object, field, or record permission.

Salesforce Knowledge stores governed articles that agents or supported audiences can use to resolve recurring questions. Administration includes article lifecycle, visibility, data categories, channels, and access according to the org's configuration. Knowledge is appropriate for reusable resolution content, not as a replacement for a Case that must track a customer's individual issue.

## Support processes and configuration choices

A support process selects the Case status values available for a record type. Use multiple processes only when the lifecycle meaningfully differs. Page layouts shape fields and actions; Lightning record pages shape components; neither substitutes for the support process. Keep statuses operational and measurable instead of creating synonyms that obscure work.

Choose purpose-built service rules before generic automation when they directly satisfy the requirement. Initial criteria-based owner routing suggests a Case assignment rule. A tailored receipt email suggests an auto-response rule. Time-based reassignment or notification suggests escalation. More complex multi-record orchestration may belong to Flow in Topic 10.

## Administrative troubleshooting

Trace one Case end to end. Record its origin and field values on creation. Confirm whether the active assignment rule was invoked and which first entry matched. Confirm owner and queue membership. Check whether the auto-response criteria and email configuration matched. For aging failures, inspect active escalation rule, entry criteria, timing basis, business hours, and whether the Case state stopped or changed escalation behavior.

For console or Knowledge visibility problems, separate app configuration from permission and channel visibility. Do not fix a missing console component by broadening record sharing, and do not fix a routing error by changing a page layout.

## Mini-scenarios

**Product intake:** Email-origin installation cases should enter a specialist pool. Email-to-Case creates the record; the active assignment rule routes matching cases to the Installation queue.

**Immediate acknowledgement:** Premium customers need a tailored receipt message. An auto-response rule chooses the email; it does not own the Case.

**Aged urgent work:** A high-priority Case still open after the supported interval must move to Tier 2 and notify a manager. Configure escalation criteria, business hours, and actions.

**Contractual target:** Customers have different contracted response commitments that must be tracked as service targets. Evaluate Entitlements and milestones rather than merely adding a status.

**Recurring answer:** Agents repeatedly solve the same supported question. Publish and govern a Knowledge article while retaining Cases for individual interactions.

## Common mistakes and exam traps

- Confusing initial assignment with time-based escalation.
- Assuming an active rule was invoked by every creation path.
- Forgetting first-match entry order.
- Using auto-response to try to change ownership.
- Treating queue ownership as proof an individual accepted the work.
- Confusing business hours with profile login hours.
- Assuming the Service Console grants permissions.
- Deploying entitlements for every simple aging requirement.
- Using Knowledge instead of tracking an individual customer issue.

## Final checklist

Can I identify the Case lifecycle and choose intake, queue, assignment, auto-response, escalation, support process, console, Knowledge, or entitlement boundary? Can I trace rule invocation, ordering, criteria, timing, and business hours? If so, I can answer: **How should Salesforce be configured to route, manage, escalate and resolve customer support work?**

## Related topics

Topic 4 owns generic layouts and Lightning pages. Topic 3 owns access. Topic 9 owns reporting and Topic 10 owns broader automation. Cross-topic context must not replace the service decision.
`} as const;
const T="service-support" as const,S="SUPPORTED" as const,q=(x:Q):Q=>x;
export const SALESFORCE_PLATFORM_ADMIN_TOPIC_06_QUIZZES:ReadonlyArray<Q>=[
q({id:"SF-PA-T06-Q01",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Case",difficulty:"easy",type:"conceptual",prompt:"Which object tracks an individual customer support issue through resolution?",answers:[{id:"A",text:"Opportunity"},{id:"B",text:"Campaign"},{id:"C",text:"Case"},{id:"D",text:"Price Book"}],correctAnswerId:"C",explanation:"A Case represents a customer issue or request and its support lifecycle. Opportunities track revenue, Campaigns marketing initiatives, and Price Books pricing. Principle: use the standard service record for individual support work. Objective SS-01, Topic 6. Review: Cases and the support lifecycle.",reviewSection:"Cases and the support lifecycle",supportStatus:S}),
q({id:"SF-PA-T06-Q02",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Queue",difficulty:"easy",type:"conceptual",prompt:"What is the primary purpose of a Case queue?",answers:[{id:"A",text:"Hold pooled work for an eligible support team"},{id:"B",text:"Define user login hours"},{id:"C",text:"Set Opportunity prices"},{id:"D",text:"Convert Leads"}],correctAnswerId:"A",explanation:"A queue can own pooled Cases for members to manage or accept. Login hours, product pricing, and lead conversion belong to different features. Queue ownership supports shared work but is not time-based escalation. Objective SS-01, Topic 6. Review: Cases and the support lifecycle.",reviewSection:"Cases and the support lifecycle",supportStatus:S}),
q({id:"SF-PA-T06-Q03",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Auto-response rule",difficulty:"easy",type:"conceptual",prompt:"Which feature sends a criteria-based acknowledgement email when a Case is received?",answers:[{id:"A",text:"Role hierarchy"},{id:"B",text:"Case auto-response rule"},{id:"C",text:"Sales process"},{id:"D",text:"Forecast hierarchy"}],correctAnswerId:"B",explanation:"A Case auto-response rule selects an acknowledgement email using ordered criteria. It does not grant access or define sales and forecasting structures. Principle: communication and ownership are separate service actions. Objective SS-02, Topic 6. Review: Case intake and responses.",reviewSection:"Case intake and responses",supportStatus:S}),
q({id:"SF-PA-T06-Q04",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Escalation rule",difficulty:"easy",type:"conceptual",prompt:"Which feature performs time-based actions when a qualifying Case remains unresolved too long?",answers:[{id:"A",text:"Lead assignment rule"},{id:"B",text:"Field dependency"},{id:"C",text:"Campaign influence"},{id:"D",text:"Case escalation rule"}],correctAnswerId:"D",explanation:"Case escalation rules evaluate qualifying cases over time and can reassign or notify. Lead assignment, field dependencies, and campaign influence solve unrelated sales or metadata needs. Objective SS-02, Topic 6. Review: Escalation, business hours, and service targets.",reviewSection:"Escalation, business hours, and service targets",supportStatus:S}),
q({id:"SF-PA-T06-Q05",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Case assignment rule",difficulty:"medium",type:"short-scenario",prompt:"New installation Cases should immediately go to a specialist pool based on Case Reason. Which configuration is most direct?",answers:[{id:"A",text:"A Campaign Member status"},{id:"B",text:"A Case assignment rule targeting the Installation queue"},{id:"C",text:"An Opportunity sales process"},{id:"D",text:"A dashboard subscription"}],correctAnswerId:"B",explanation:"A Case assignment rule uses ordered criteria to select an initial user or queue owner, matching reason-based routing. Campaign, Opportunity, and dashboard features cannot route support ownership. Objective SS-01, Topic 6. Review: Queues and assignment rules.",reviewSection:"Queues and assignment rules",supportStatus:S}),
q({id:"SF-PA-T06-Q06",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Assignment versus escalation",difficulty:"medium",type:"administrative-decision",prompt:"A Case is routed correctly at creation but must move to Tier 2 if still open after four support hours. Which second mechanism is needed?",answers:[{id:"A",text:"An escalation rule with a timed action"},{id:"B",text:"Another page layout"},{id:"C",text:"A lead conversion mapping"},{id:"D",text:"A custom price book"}],correctAnswerId:"A",explanation:"Initial assignment already succeeded; the new requirement is a time-based response to aging, which fits escalation. Layouts, lead mapping, and price books cannot evaluate unresolved Case age. Objective SS-02, Topic 6. Review: Escalation, business hours, and service targets.",reviewSection:"Escalation, business hours, and service targets",supportStatus:S}),
q({id:"SF-PA-T06-Q07",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Business hours",difficulty:"medium",type:"configuration-choice",prompt:"An escalation timer must exclude weekends and company holidays. What context should the escalation configuration use?",answers:[{id:"A",text:"Profile login hours"},{id:"B",text:"Opportunity close dates"},{id:"C",text:"Appropriate business hours and holidays"},{id:"D",text:"Campaign start date only"}],correctAnswerId:"C",explanation:"Business hours and holidays model supported operating time for service timing. Profile login hours restrict user entry and do not calculate service commitments; sales and campaign dates are unrelated. Objective SS-02, Topic 6. Review: Escalation, business hours, and service targets.",reviewSection:"Escalation, business hours, and service targets",supportStatus:S}),
q({id:"SF-PA-T06-Q08",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Email-to-Case",difficulty:"medium",type:"configuration-choice",prompt:"Support wants inbound messages to a service address captured as Cases for agent work. Which intake capability fits?",answers:[{id:"A",text:"Web-to-Lead"},{id:"B",text:"Collaborative Forecasts"},{id:"C",text:"Path"},{id:"D",text:"Email-to-Case"}],correctAnswerId:"D",explanation:"Email-to-Case turns supported inbound service email into Cases. Web-to-Lead creates prospects, while Forecasts and Path support sales. Intake creates the Case; assignment and response remain separate configuration. Objective SS-01, Topic 6. Review: Case intake and responses.",reviewSection:"Case intake and responses",supportStatus:S}),
q({id:"SF-PA-T06-Q09",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Support process",difficulty:"medium",type:"configuration-choice",prompt:"Billing Cases and Technical Cases require different allowable status values. Which feature should be associated through their record types?",answers:[{id:"A",text:"Support processes"},{id:"B",text:"Trusted IP ranges"},{id:"C",text:"Price books"},{id:"D",text:"Territory models"}],correctAnswerId:"A",explanation:"A support process determines the Case status values available and is associated through record types. Network, pricing, and territory configurations do not define service lifecycle statuses. Objective SS-01, Topic 6. Review: Support processes and configuration choices.",reviewSection:"Support processes and configuration choices",supportStatus:S}),
q({id:"SF-PA-T06-Q10",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Service Console",difficulty:"medium",type:"administrative-decision",prompt:"Agents need a focused workspace with tabbed service records and contextual productivity components. Which experience is designed for this?",answers:[{id:"A",text:"Schema Builder"},{id:"B",text:"The Service Console"},{id:"C",text:"Data Export"},{id:"D",text:"A Campaign hierarchy"}],correctAnswerId:"B",explanation:"The Service Console provides an agent-focused workspace with service records and contextual tools. Schema Builder models data, export extracts it, and Campaign hierarchies organize marketing. The console does not override permissions. Objective SS-01, Topic 6. Review: Service Console and Knowledge.",reviewSection:"Service Console and Knowledge",supportStatus:S}),
q({id:"SF-PA-T06-Q11",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Knowledge",difficulty:"medium",type:"best-practice",prompt:"Agents repeatedly resolve the same supported question and need governed reusable guidance. What should the administrator evaluate?",answers:[{id:"A",text:"A separate Opportunity for each answer"},{id:"B",text:"A new login policy"},{id:"C",text:"Salesforce Knowledge articles and their lifecycle and visibility"},{id:"D",text:"Deleting the related Cases"}],correctAnswerId:"C",explanation:"Knowledge provides governed reusable resolution content with lifecycle and visibility controls. Opportunities and login policy are unrelated, while deleting Cases loses individual interaction history. Objective SS-02, Topic 6. Review: Service Console and Knowledge.",reviewSection:"Service Console and Knowledge",supportStatus:S}),
q({id:"SF-PA-T06-Q12",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Assignment invocation",difficulty:"medium",type:"troubleshooting",prompt:"Cases created by an integration ignore a correct active assignment rule. What should be verified first?",answers:[{id:"A",text:"Whether users changed locale"},{id:"B",text:"Whether the Opportunity forecast is active"},{id:"C",text:"Whether Campaign statuses are responded"},{id:"D",text:"Whether the integration creation path invokes the active assignment rule"}],correctAnswerId:"D",explanation:"An active rule does not guarantee every creation path invokes it, so start with invocation before editing criteria. Forecasts, campaign response, and locale do not control Case routing. Objective SS-01, Topic 6. Review: Administrative troubleshooting.",reviewSection:"Administrative troubleshooting",supportStatus:S}),
q({id:"SF-PA-T06-Q13",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Rule order",difficulty:"medium",type:"troubleshooting",prompt:"A high-priority hardware Case goes to the general queue because it matches two assignment entries. What configuration detail most likely explains the result?",answers:[{id:"A",text:"The user's time zone"},{id:"B",text:"The first matching assignment-rule entry wins"},{id:"C",text:"The corporate currency"},{id:"D",text:"The Opportunity stage probability"}],correctAnswerId:"B",explanation:"Case assignment entries are ordered, and the first match determines ownership. A broad general entry placed too early can capture specialized work. Time zone, currency, and opportunity probability do not route Cases. Objective SS-01, Topic 6. Review: Queues and assignment rules.",reviewSection:"Queues and assignment rules",supportStatus:S}),
q({id:"SF-PA-T06-Q14",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Entitlement boundary",difficulty:"medium",type:"configuration-choice",prompt:"Different customers have contractual first-response targets that must be tracked as service obligations. Which capability should be evaluated?",answers:[{id:"A",text:"Campaign influence"},{id:"B",text:"Lead queues"},{id:"C",text:"Opportunity products"},{id:"D",text:"Entitlements and milestones"}],correctAnswerId:"D",explanation:"Entitlements can model support eligibility and milestones can track contractual service targets. Campaigns, lead queues, and opportunity products do not represent support commitments. Use this capability when the contractual model warrants it. Objective SS-02, Topic 6. Review: Escalation, business hours, and service targets.",reviewSection:"Escalation, business hours, and service targets",supportStatus:S}),
q({id:"SF-PA-T06-Q15",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Auto-response boundary",difficulty:"hard",type:"short-scenario",prompt:"Premium Cases need an immediate branded receipt, initial routing to a premium queue, and manager notification after two support hours. Which configuration maps each requirement correctly?",answers:[{id:"A",text:"Auto-response rule, assignment rule, and escalation rule respectively"},{id:"B",text:"One page layout performs all three"},{id:"C",text:"Campaign, sales process, and forecast respectively"},{id:"D",text:"One queue performs communication and timing automatically"}],correctAnswerId:"A",explanation:"Auto-response handles the receipt, assignment selects initial ownership, and escalation performs time-based action. A layout or queue alone does not cover communication and timing; sales features are out of scope. Objective SS-02 with SS-01 context, Topic 6. Review: Support processes and configuration choices.",reviewSection:"Support processes and configuration choices",supportStatus:S}),
q({id:"SF-PA-T06-Q16",topicSlug:T,objectiveId:"SS-01", blueprintDomain: "service-support",concept:"Queue troubleshooting",difficulty:"hard",type:"troubleshooting",prompt:"Cases correctly enter a regional queue, but agents say none can take the work. Which investigation best preserves the assignment/access boundary?",answers:[{id:"A",text:"Inspect queue membership, supported object, work visibility, and operating procedure before changing routing"},{id:"B",text:"Delete the active assignment rule immediately"},{id:"C",text:"Create duplicate Cases owned by every agent"},{id:"D",text:"Change all Opportunity stages"}],correctAnswerId:"A",explanation:"Correct queue ownership suggests routing worked; next inspect who belongs to the queue and how members see and accept work. Deleting routing, duplicating records, or changing sales stages does not isolate the issue. Objective SS-01, Topic 6. Review: Queues and assignment rules.",reviewSection:"Queues and assignment rules",supportStatus:S}),
q({id:"SF-PA-T06-Q17",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Escalation troubleshooting",difficulty:"hard",type:"troubleshooting",prompt:"An open urgent Case never escalates after the expected interval. What is the strongest diagnostic sequence?",answers:[{id:"A",text:"Make Cases public and reset agent passwords"},{id:"B",text:"Change the Case page layout only"},{id:"C",text:"Check active escalation rule, ordered criteria, timing basis, business hours, and Case state changes"},{id:"D",text:"Replace the Case with a Lead"}],correctAnswerId:"C",explanation:"Escalation depends on activation, entry matching, timing, business hours, and record state, so trace those layers with the actual Case. Sharing, passwords, layouts, and Leads do not diagnose timed service behavior. Objective SS-02, Topic 6. Review: Administrative troubleshooting.",reviewSection:"Administrative troubleshooting",supportStatus:S}),
q({id:"SF-PA-T06-Q18",topicSlug:T,objectiveId:"SS-02", blueprintDomain: "service-support",concept:"Purpose-built automation",difficulty:"hard",type:"administrative-decision",prompt:"An architect proposes one complex Flow for initial Case ownership, acknowledgement, and simple age-based reassignment. What should the administrator evaluate first?",answers:[{id:"A",text:"Whether a Campaign hierarchy can route support"},{id:"B",text:"Whether a custom Product can replace the Case"},{id:"C",text:"Whether all users can receive Modify All Data"},{id:"D",text:"Whether purpose-built assignment, auto-response, and escalation rules satisfy the requirements more clearly"}],correctAnswerId:"D",explanation:"Purpose-built Case rules directly express routing, acknowledgement, and age-based escalation and should be evaluated before broader automation. Products, excessive permissions, and Campaigns do not model the requirement. Objective SS-02, Topic 6. Review: Support processes and configuration choices.",reviewSection:"Support processes and configuration choices",supportStatus:S}),
];
