import type {Category,Decision,Difficulty,Localized,Scenario} from "./types";
const L=(it:string,en:string,fr:string,es:string):Localized=>({it,en,fr,es});
const safe=L("Contesto autorizzato e comportamento normale.","Authorized context and normal behavior.","Contexte autorisé et comportement normal.","Contexto autorizado y comportamiento normal.");
const danger=L("Contesto non autorizzato o comportamento chiaramente anomalo.","Unauthorized context or clearly anomalous behavior.","Contexte non autorisé ou comportement clairement anormal.","Contexto no autorizado o comportamiento claramente anómalo.");
const rows:[string,Category,Difficulty,string,number,"TCP"|"UDP",Decision,Localized,Localized,Localized][]=[
["https-valid", "web","basic","HTTPS",443,"TCP","allow",L("Sito aziendale noto","Known company site","Site d’entreprise connu","Sitio corporativo conocido"),L("Certificato valido, dominio previsto","Valid certificate, expected domain","Certificat valide, domaine prévu","Certificado válido, dominio esperado"),safe],
["https-expired","web","basic","HTTPS",443,"TCP","block",L("Portale pagamenti","Payment portal","Portail de paiement","Portal de pagos"),L("Certificato scaduto e nome non corrispondente","Expired certificate and name mismatch","Certificat expiré et nom incorrect","Certificado caducado y nombre incorrecto"),danger],
["dns-corp","dns","basic","DNS",53,"UDP","allow",L("Client interno → resolver aziendale","Internal client → company resolver","Client interne → résolveur d’entreprise","Cliente interno → resolver corporativo"),L("Volume normale, resolver configurato","Normal volume, configured resolver","Volume normal, résolveur configuré","Volumen normal, resolver configurado"),safe],
["dns-tunnel","dns","intermediate","DNS",53,"UDP","block",L("Host interno → resolver sconosciuto","Internal host → unknown resolver","Hôte interne → résolveur inconnu","Host interno → resolver desconocido"),L("Query molto lunghe e frequenza anomala","Very long queries and anomalous frequency","Requêtes très longues et fréquence anormale","Consultas muy largas y frecuencia anómala"),danger],
["ntp-auth","admin","basic","NTP",123,"UDP","allow",L("Server interno → time server autorizzato","Internal server → authorized time server","Serveur interne → serveur de temps autorisé","Servidor interno → servidor horario autorizado"),L("Sincronizzazione pianificata","Scheduled synchronization","Synchronisation planifiée","Sincronización programada"),safe],
["ssh-admin","remote","basic","SSH",22,"TCP","allow",L("IP VPN dell’amministratore","Administrator VPN IP","IP VPN de l’administrateur","IP VPN del administrador"),L("Chiave valida, accesso approvato","Valid key, approved access","Clé valide, accès approuvé","Clave válida, acceso aprobado"),safe],
["ssh-brute","remote","basic","SSH",22,"TCP","block",L("Origine Internet sconosciuta","Unknown Internet source","Source Internet inconnue","Origen de Internet desconocido"),L("42 tentativi falliti in un minuto","42 failed attempts in one minute","42 échecs en une minute","42 intentos fallidos en un minuto"),danger],
["rdp-internet","remote","basic","RDP",3389,"TCP","block",L("Internet → workstation","Internet → workstation","Internet → poste de travail","Internet → estación de trabajo"),L("Servizio esposto senza autorizzazione","Service exposed without authorization","Service exposé sans autorisation","Servicio expuesto sin autorización"),danger],
["smtp-relay","mail","intermediate","SMTP",25,"TCP","block",L("Host esterno → relay interno","External host → internal relay","Hôte externe → relais interne","Host externo → relay interno"),L("Relay non autenticato verso molti destinatari","Unauthenticated relay to many recipients","Relais non authentifié vers de nombreux destinataires","Relay no autenticado a muchos destinatarios"),danger],
["mail-submit","mail","basic","SMTP Submission",587,"TCP","allow",L("Client gestito → mail gateway","Managed client → mail gateway","Client géré → passerelle mail","Cliente gestionado → pasarela de correo"),L("TLS e autenticazione validi","Valid TLS and authentication","TLS et authentification valides","TLS y autenticación válidos"),safe],
["smb-public","file","basic","SMB",445,"TCP","block",L("Rete pubblica → file server","Public network → file server","Réseau public → serveur de fichiers","Red pública → servidor de archivos"),L("Origine non attendibile, nessuna VPN","Untrusted source, no VPN","Source non fiable, aucun VPN","Origen no fiable, sin VPN"),danger],
["backup","file","basic","SFTP",22,"TCP","allow",L("Backup agent → server interno","Backup agent → internal server","Agent de sauvegarde → serveur interne","Agente de copia → servidor interno"),L("Job pianificato e chiave dedicata","Scheduled job and dedicated key","Tâche planifiée et clé dédiée","Tarea programada y clave dedicada"),safe],
["ftp-creds","file","intermediate","FTP",21,"TCP","block",L("Client remoto → server legacy","Remote client → legacy server","Client distant → serveur ancien","Cliente remoto → servidor heredado"),L("Credenziali trasmesse senza cifratura","Credentials sent without encryption","Identifiants transmis sans chiffrement","Credenciales enviadas sin cifrar"),danger],
["signed-update","web","basic","HTTPS",443,"TCP","allow",L("Endpoint gestito → repository ufficiale","Managed endpoint → official repository","Terminal géré → dépôt officiel","Endpoint gestionado → repositorio oficial"),L("Pacchetto firmato, hash verificato","Signed package, verified hash","Paquet signé, empreinte vérifiée","Paquete firmado, hash verificado"),safe],
["unknown-exe","suspicious","basic","Custom",49152,"TCP","block",L("Eseguibile sconosciuto → Internet","Unknown executable → Internet","Exécutable inconnu → Internet","Ejecutable desconocido → Internet"),L("Destinazione appena registrata, processo non approvato","Newly registered destination, unapproved process","Destination récemment créée, processus non approuvé","Destino recién registrado, proceso no aprobado"),danger],
["port-scan","suspicious","basic","TCP scan",1024,"TCP","block",L("Singolo host esterno","Single external host","Hôte externe unique","Un host externo"),L("Tentativi rapidi su 200 porte","Rapid attempts across 200 ports","Tentatives rapides sur 200 ports","Intentos rápidos en 200 puertos"),danger],
["c2","suspicious","intermediate","TLS",443,"TCP","block",L("Endpoint → indicatore C2 noto","Endpoint → known C2 indicator","Terminal → indicateur C2 connu","Endpoint → indicador C2 conocido"),L("Destinazione presente nella blocklist aziendale","Destination on company blocklist","Destination dans la liste de blocage","Destino en la lista de bloqueo"),danger],
["db-app","database","basic","PostgreSQL",5432,"TCP","allow",L("Application server → database interno","Application server → internal database","Serveur applicatif → base interne","Servidor de aplicación → base interna"),L("Account di servizio e segmento previsti","Expected service account and segment","Compte de service et segment prévus","Cuenta de servicio y segmento previstos"),safe],
["db-public","database","basic","MySQL",3306,"TCP","block",L("Internet → database","Internet → database","Internet → base de données","Internet → base de datos"),L("Accesso diretto pubblico non autorizzato","Unauthorized direct public access","Accès public direct non autorisé","Acceso público directo no autorizado"),danger],
["dhcp","admin","basic","DHCP",67,"UDP","allow",L("Client VLAN → DHCP autorizzato","VLAN client → authorized DHCP","Client VLAN → DHCP autorisé","Cliente VLAN → DHCP autorizado"),L("Offerta dal server configurato","Offer from configured server","Offre du serveur configuré","Oferta del servidor configurado"),safe],
["rogue-dhcp","admin","intermediate","DHCP",67,"UDP","block",L("Laptop utente → client VLAN","User laptop → VLAN clients","Portable utilisateur → clients VLAN","Portátil de usuario → clientes VLAN"),L("Offerte DHCP da server non autorizzato","DHCP offers from unauthorized server","Offres DHCP d’un serveur non autorisé","Ofertas DHCP de servidor no autorizado"),danger],
["vpn","remote","intermediate","IPsec NAT-T",4500,"UDP","allow",L("Laptop gestito → gateway VPN","Managed laptop → VPN gateway","Portable géré → passerelle VPN","Portátil gestionado → pasarela VPN"),L("Certificato dispositivo valido e utente MFA","Valid device certificate and user MFA","Certificat appareil valide et MFA","Certificado válido y MFA"),safe],
["snmpv2-public","admin","intermediate","SNMP",161,"UDP","block",L("Internet → router","Internet → router","Internet → routeur","Internet → router"),L("Community predefinita e gestione esposta","Default community and exposed management","Communauté par défaut et gestion exposée","Comunidad predeterminada y gestión expuesta"),danger],
["snmpv3","admin","advanced","SNMPv3",161,"UDP","allow",L("NMS interno → switch gestito","Internal NMS → managed switch","NMS interne → commutateur géré","NMS interno → switch gestionado"),L("Autenticazione e cifratura, ACL autorizzata","Authentication and encryption, authorized ACL","Authentification, chiffrement et ACL autorisée","Autenticación, cifrado y ACL autorizada"),safe],
["kerberos","auth","intermediate","Kerberos",88,"TCP","allow",L("Workstation di dominio → domain controller","Domain workstation → domain controller","Poste du domaine → contrôleur","Estación de dominio → controlador"),L("Richiesta ticket nel dominio previsto","Ticket request in expected domain","Demande de ticket dans le domaine prévu","Solicitud de ticket en dominio esperado"),safe],
["bruteforce-web","auth","intermediate","HTTPS",443,"TCP","block",L("Bot esterno → login amministrativo","External bot → admin login","Bot externe → connexion admin","Bot externo → acceso administrativo"),L("300 password per lo stesso account","300 passwords for one account","300 mots de passe pour un compte","300 contraseñas para una cuenta"),danger],
["radius","auth","advanced","RADIUS",1812,"UDP","allow",L("Wi-Fi controller → RADIUS interno","Wi-Fi controller → internal RADIUS","Contrôleur Wi-Fi → RADIUS interne","Controlador Wi-Fi → RADIUS interno"),L("Client registrato e policy prevista","Registered client and expected policy","Client enregistré et politique prévue","Cliente registrado y política esperada"),safe],
["syslog","admin","advanced","Syslog TLS",6514,"TCP","allow",L("Firewall → SIEM interno","Firewall → internal SIEM","Pare-feu → SIEM interne","Firewall → SIEM interno"),L("Canale TLS autenticato, destinazione prevista","Authenticated TLS channel, expected destination","Canal TLS authentifié, destination prévue","Canal TLS autenticado, destino esperado"),safe],
["telnet","remote","intermediate","Telnet",23,"TCP","block",L("Admin → apparato di produzione","Admin → production device","Admin → équipement de production","Admin → dispositivo de producción"),L("Sessione con credenziali non cifrate; SSH disponibile","Unencrypted credentials; SSH available","Identifiants non chiffrés ; SSH disponible","Credenciales sin cifrar; SSH disponible"),danger],
["waf-health","firewall","advanced","HTTPS",8443,"TCP","allow",L("Load balancer → health endpoint","Load balancer → health endpoint","Répartiteur → endpoint de santé","Balanceador → endpoint de salud"),L("Origine in allowlist, percorso e frequenza previsti","Allowlisted source, expected path and rate","Source autorisée, chemin et fréquence prévus","Origen permitido, ruta y frecuencia esperados"),safe],
["egress-policy","firewall","advanced","HTTPS",443,"TCP","block",L("Server database → file sharing personale","Database server → personal file sharing","Serveur BDD → partage personnel","Servidor BD → archivos personales"),L("Destinazione vietata dalla policy e upload anomalo","Policy-blocked destination and anomalous upload","Destination interdite et envoi anormal","Destino prohibido y subida anómala"),danger],
["dns-tcp-zone","dns","advanced","DNS",53,"TCP","allow",L("Secondario DNS autorizzato → primario","Authorized DNS secondary → primary","DNS secondaire autorisé → primaire","DNS secundario autorizado → primario"),L("Trasferimento zona autenticato e pianificato","Authenticated scheduled zone transfer","Transfert de zone authentifié et planifié","Transferencia de zona autenticada y programada"),safe],
["zone-transfer","dns","advanced","DNS",53,"TCP","block",L("Host esterno sconosciuto → DNS autoritativo","Unknown external host → authoritative DNS","Hôte externe inconnu → DNS autoritaire","Host externo desconocido → DNS autoritativo"),L("Richiesta AXFR non autorizzata","Unauthorized AXFR request","Requête AXFR non autorisée","Solicitud AXFR no autorizada"),danger],
["upload-exe","file","advanced","HTTPS",443,"TCP","block",L("Utente standard → portale condiviso","Standard user → shared portal","Utilisateur standard → portail partagé","Usuario estándar → portal compartido"),L("Eseguibile non autorizzato, hash sconosciuto","Unauthorized executable, unknown hash","Exécutable non autorisé, empreinte inconnue","Ejecutable no autorizado, hash desconocido"),danger],
["api-high-port","web","advanced","HTTPS API",8443,"TCP","allow",L("App interna → API inventory","Internal app → inventory API","App interne → API inventaire","App interna → API inventario"),L("mTLS valido e porta documentata","Valid mTLS and documented port","mTLS valide et port documenté","mTLS válido y puerto documentado"),safe]
];
export const SCENARIOS:readonly Scenario[]=rows.map(([id,category,difficulty,service,port,transport,decision,origin,description,explanation])=>({id,category,difficulty,service,port,transport,decision,origin,description,explanation,indicators:decision==="allow"?safe:danger,weight:1}));
