import type { Locale } from "@/lib/quiz-types";

export const moduleLabels = {
  it: {
    sectionsCompleted: (done: number, total: number) => `${done} di ${total} sezioni completate`,
    continue: "Continua",
    markComplete: "Segna come completato",
    completed: "Completata",
    next: "Successiva",
    previous: "Precedente",
    backToOutline: "Torna all'indice",
    moduleOutline: "Indice del modulo",
    statusDone: "completata",
    statusCurrent: "in corso",
    statusTodo: "da iniziare",
    assessmentTitle: "Valutazione",
    summaryTitle: "Riepilogo del modulo",
    keyTerms: "Termini importanti",
    commonMistakes: "Errori frequenti",
    keyPoints: "Punti chiave",
    scoreLabel: "Punteggio",
    finishModule: "Concludi il modulo",
    moduleCompletedBadge: "Modulo completato",
    startAssessment: "Inizia la valutazione",
  },
  en: {
    sectionsCompleted: (done: number, total: number) => `${done} of ${total} sections completed`,
    continue: "Continue",
    markComplete: "Mark as completed",
    completed: "Completed",
    next: "Next",
    previous: "Previous",
    backToOutline: "Back to outline",
    moduleOutline: "Module outline",
    statusDone: "completed",
    statusCurrent: "in progress",
    statusTodo: "not started",
    assessmentTitle: "Assessment",
    summaryTitle: "Module summary",
    keyTerms: "Key terms",
    commonMistakes: "Common mistakes",
    keyPoints: "Key points",
    scoreLabel: "Score",
    finishModule: "Finish module",
    moduleCompletedBadge: "Module completed",
    startAssessment: "Start assessment",
  },
  fr: {
    sectionsCompleted: (done: number, total: number) => `${done} sur ${total} sections terminées`,
    continue: "Continuer",
    markComplete: "Marquer comme terminé",
    completed: "Terminée",
    next: "Suivante",
    previous: "Précédente",
    backToOutline: "Retour au sommaire",
    moduleOutline: "Sommaire du module",
    statusDone: "terminée",
    statusCurrent: "en cours",
    statusTodo: "à commencer",
    assessmentTitle: "Évaluation",
    summaryTitle: "Résumé du module",
    keyTerms: "Termes importants",
    commonMistakes: "Erreurs fréquentes",
    keyPoints: "Points clés",
    scoreLabel: "Score",
    finishModule: "Terminer le module",
    moduleCompletedBadge: "Module terminé",
    startAssessment: "Commencer l'évaluation",
  },
  es: {
    sectionsCompleted: (done: number, total: number) => `${done} de ${total} secciones completadas`,
    continue: "Continuar",
    markComplete: "Marcar como completada",
    completed: "Completada",
    next: "Siguiente",
    previous: "Anterior",
    backToOutline: "Volver al índice",
    moduleOutline: "Índice del módulo",
    statusDone: "completada",
    statusCurrent: "en curso",
    statusTodo: "sin empezar",
    assessmentTitle: "Evaluación",
    summaryTitle: "Resumen del módulo",
    keyTerms: "Términos importantes",
    commonMistakes: "Errores frecuentes",
    keyPoints: "Puntos clave",
    scoreLabel: "Puntuación",
    finishModule: "Finalizar módulo",
    moduleCompletedBadge: "Módulo completado",
    startAssessment: "Iniciar evaluación",
  },
} as const satisfies Record<Locale, unknown>;

export type ModuleLabels = (typeof moduleLabels)[Locale];
