import Link from "next/link";
import { ArrowRight, Network, ShieldCheck, Table2 } from "lucide-react";
import type { Locale } from "@/lib/paths";

const copy = {
  it: { subtitle:"Impara facendo, un'attività alla volta", body:"Scegli un laboratorio e lavora in un ambiente simulato. Ogni percorso ha una pagina dedicata, obiettivi progressivi e verifica delle attività.", badge:"3 laboratori disponibili", open:"Apri il laboratorio", labs:[
    {slug:"spreadsheets",title:"Completa il report vendite",category:"Fogli di calcolo",duration:"5 min",description:"Inserisci formule, calcola totale e media e applica la formattazione corretta."},
    {slug:"networking",title:"Diagnostica una connessione",category:"Networking",duration:"6 min",description:"Usa un terminale simulato per isolare e correggere un problema DNS."},
    {slug:"phishing",title:"Analizza un'email sospetta",category:"Cybersecurity",duration:"5 min",description:"Individua gli indicatori di phishing e scegli la risposta più sicura."}]},
  en: { subtitle:"Learn by doing, one task at a time", body:"Choose a lab and work in a simulated environment. Each path has its own page, progressive objectives, and task validation.", badge:"3 labs available", open:"Open lab", labs:[
    {slug:"spreadsheets",title:"Complete the sales report",category:"Spreadsheets",duration:"5 min",description:"Enter formulas, calculate total and average, and apply the correct formatting."},
    {slug:"networking",title:"Diagnose a connection",category:"Networking",duration:"6 min",description:"Use a simulated terminal to isolate and fix a DNS problem."},
    {slug:"phishing",title:"Analyze a suspicious email",category:"Cybersecurity",duration:"5 min",description:"Identify phishing indicators and choose the safest response."}]},
  fr: { subtitle:"Apprenez par la pratique, une tâche à la fois", body:"Choisissez un laboratoire et travaillez dans un environnement simulé. Chaque parcours dispose de sa propre page et d'objectifs progressifs.", badge:"3 labs disponibles", open:"Ouvrir le lab", labs:[
    {slug:"spreadsheets",title:"Compléter le rapport des ventes",category:"Tableurs",duration:"5 min",description:"Saisissez des formules, calculez le total et la moyenne, puis appliquez le bon format."},
    {slug:"networking",title:"Diagnostiquer une connexion",category:"Réseau",duration:"6 min",description:"Utilisez un terminal simulé pour isoler et corriger un problème DNS."},
    {slug:"phishing",title:"Analyser un e-mail suspect",category:"Cybersécurité",duration:"5 min",description:"Identifiez les indices de phishing et choisissez la réponse la plus sûre."}]},
  es: { subtitle:"Aprende haciendo, una tarea a la vez", body:"Elige un laboratorio y trabaja en un entorno simulado. Cada recorrido tiene su propia página, objetivos progresivos y validación.", badge:"3 labs disponibles", open:"Abrir lab", labs:[
    {slug:"spreadsheets",title:"Completa el informe de ventas",category:"Hojas de cálculo",duration:"5 min",description:"Introduce fórmulas, calcula total y promedio y aplica el formato correcto."},
    {slug:"networking",title:"Diagnostica una conexión",category:"Redes",duration:"6 min",description:"Usa una terminal simulada para aislar y corregir un problema DNS."},
    {slug:"phishing",title:"Analiza un correo sospechoso",category:"Ciberseguridad",duration:"5 min",description:"Identifica señales de phishing y elige la respuesta más segura."}]},
} as const;
const icons=[Table2,Network,ShieldCheck];

export default function InteractiveLabsLanding({lang}:{lang:Locale}){const t=copy[lang];const base=lang==="en"?"/interactive-labs":`/${lang}/interactive-labs`;return <main id="main" className="min-h-[70vh] bg-gradient-to-b from-indigo-50 via-white to-white px-4 py-14 sm:py-16"><div className="mx-auto max-w-6xl"><header className="mx-auto max-w-3xl text-center"><span className="inline-flex rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-800">{t.badge}</span><h1 className="mt-5 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Interactive Labs</h1><p className="mt-4 text-xl font-medium text-indigo-700">{t.subtitle}</p><p className="mt-5 leading-7 text-slate-600">{t.body}</p></header><section className="mt-12 grid gap-5 md:grid-cols-3" aria-label="Interactive labs">{t.labs.map((lab,index)=>{const Icon=icons[index];return <article key={lab.slug} className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><Icon size={22} aria-hidden="true"/></span><span className="text-xs font-semibold text-slate-500">{lab.duration}</span></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-indigo-700">{lab.category}</p><h2 className="mt-2 text-xl font-semibold text-slate-950">{lab.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{lab.description}</p><Link href={`${base}/${lab.slug}`} className="mt-6 inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700">{t.open}<ArrowRight size={17}/></Link></article>})}</section></div></main>}
