export const labSlugs = [
  "spreadsheets",
  "networking",
  "phishing",
  "subnetting",
  "password-security",
  "linux-permissions",
  "sql-select",
  "docker-lifecycle",
  "cloud-storage-security",
  "ai-prompt-safety",
  "python-data-cleanup",
  "windows-server-users",
  "powershell-pipeline",
  "word-document",
  "ccst-networking-ip-configuration",
  "ccst-networking-devices-protocols",
  "ccst-networking-dns-dhcp",
  "ccst-networking-subnetting",
  "ccst-networking-ping-traceroute",
  "ccst-networking-office-offline",
  "ccst-networking-switch-vlan-configuration",
  "ccst-networking-secure-guest-wifi",
  "ccst-networking-wireless-performance",
  "ccst-networking-branch-recovery-capstone",
  "ccst-cybersecurity-classify-the-incident",
  "ccst-cybersecurity-spot-the-exposed-device",
  "ccst-cybersecurity-write-the-acl",
  "ccst-cybersecurity-investigate-with-netstat-tcpdump",
  "ccst-cybersecurity-malware-remediation",
  "ccst-cybersecurity-recon-passive-active",
  "ccst-cybersecurity-scan-to-risk",
  "ccst-cybersecurity-escalate-or-not",
  "ccst-cybersecurity-full-incident-response",
] as const;

export type LabSlug = (typeof labSlugs)[number];
