export const labSlugs = [
  "spreadsheets",
  "networking",
  "phishing",
  "subnetting",
  "password-security",
  "linux-permissions",
  "sql-select",
  "docker-lifecycle",
  "cloud-storage-security",
  "ai-prompt-safety",
  "python-data-cleanup",
  "windows-server-users",
  "powershell-pipeline",
  "word-document",
  "ccst-networking-ip-configuration",
  "ccst-networking-devices-protocols",
  "ccst-networking-dns-dhcp",
  "ccst-networking-subnetting",
  "ccst-networking-ping-traceroute",
  "ccst-networking-office-offline",
  "ccst-networking-switch-vlan-configuration",
  "ccst-networking-secure-guest-wifi",
  "ccst-networking-wireless-performance",
  "ccst-networking-branch-recovery-capstone",
] as const;

export type LabSlug = (typeof labSlugs)[number];
