"use client";

import { useState } from "react";
import { CheckCircle2, Clock3, Lightbulb, RotateCcw, Terminal } from "lucide-react";
import type { Locale } from "@/lib/paths";
import type { LabSlug } from "./lab-config";

type Localized = Record<Locale, string>;
type Step = { task: Localized; context: Localized; options: Localized[]; correct: number; explanation: Localized };
type Challenge = { eyebrow: string; title: Localized; intro: Localized; accent: string; panel: string; steps: Step[] };
const l = (it: string, en: string, fr: string, es: string): Localized => ({ it, en, fr, es });

export const scenarioChallenges: Partial<Record<LabSlug, Challenge>> = {
  "word-document": {
    eyebrow: "Microsoft Word Lab", accent: "from-blue-950 to-blue-700", panel: "border-blue-200 bg-blue-50",
    title: l("Crea un documento professionale", "Create a professional document", "Créer un document professionnel", "Crea un documento profesional"),
    intro: l("Struttura un report con stili, interruzioni e indice automatico.", "Structure a report with styles, page breaks and an automatic table of contents.", "Structurez un rapport avec styles, sauts de page et sommaire automatique.", "Estructura un informe con estilos, saltos de página e índice automático."),
    steps: [
      { task: l("Formatta il titolo del primo capitolo", "Format the first chapter title", "Mettez en forme le titre du premier chapitre", "Da formato al título del primer capítulo"), context: l("Testo selezionato: Analisi trimestrale", "Selected text: Quarterly analysis", "Texte sélectionné : Analyse trimestrielle", "Texto seleccionado: Análisis trimestral"), options: [l("Applica lo stile Titolo 1", "Apply the Heading 1 style", "Appliquer le style Titre 1", "Aplicar el estilo Título 1"), l("Aumenta manualmente il font a 24", "Manually increase the font to 24", "Augmenter manuellement la police à 24", "Aumentar manualmente la fuente a 24"), l("Inserisci una casella di testo", "Insert a text box", "Insérer une zone de texte", "Insertar un cuadro de texto")], correct: 0, explanation: l("Gli stili mantengono la formattazione coerente e alimentano l'indice automatico.", "Styles keep formatting consistent and feed the automatic table of contents.", "Les styles assurent une mise en forme cohérente et alimentent le sommaire automatique.", "Los estilos mantienen un formato coherente y alimentan el índice automático.") },
      { task: l("Inizia il capitolo successivo su una nuova pagina", "Start the next chapter on a new page", "Commencez le chapitre suivant sur une nouvelle page", "Inicia el capítulo siguiente en una página nueva"), context: l("Il cursore è prima del titolo Conclusioni", "The cursor is before the Conclusions heading", "Le curseur est avant le titre Conclusions", "El cursor está antes del título Conclusiones"), options: [l("Premi Invio fino alla pagina seguente", "Press Enter until the next page", "Appuyer sur Entrée jusqu'à la page suivante", "Pulsar Intro hasta la página siguiente"), l("Inserisci un'interruzione di pagina", "Insert a page break", "Insérer un saut de page", "Insertar un salto de página"), l("Aumenta il margine superiore", "Increase the top margin", "Augmenter la marge supérieure", "Aumentar el margen superior")], correct: 1, explanation: l("L'interruzione mantiene stabile l'impaginazione anche quando il testo precedente cambia.", "A page break keeps the layout stable when preceding text changes.", "Un saut de page stabilise la mise en page lorsque le texte précédent change.", "Un salto de página mantiene el diseño estable cuando cambia el texto anterior.") },
      { task: l("Genera l'indice del documento", "Generate the document table of contents", "Générez le sommaire du document", "Genera el índice del documento"), context: l("Tutti i capitoli usano gli stili Titolo", "All chapters use Heading styles", "Tous les chapitres utilisent les styles Titre", "Todos los capítulos usan estilos de Título"), options: [l("Riferimenti → Sommario automatico", "References → Automatic Table of Contents", "Références → Table des matières automatique", "Referencias → Tabla de contenido automática"), l("Inserisci → Tabella", "Insert → Table", "Insertion → Tableau", "Insertar → Tabla"), l("Revisione → Conteggio parole", "Review → Word Count", "Révision → Statistiques", "Revisar → Contar palabras")], correct: 0, explanation: l("Word costruisce e aggiorna l'indice usando la gerarchia degli stili Titolo.", "Word builds and updates the table of contents from the Heading style hierarchy.", "Word crée et met à jour le sommaire à partir de la hiérarchie des styles Titre.", "Word crea y actualiza el índice usando la jerarquía de estilos de Título.") },
    ],
  },
  subnetting: {
    eyebrow: "Networking Lab", accent: "from-sky-900 to-indigo-900", panel: "border-sky-200 bg-sky-50",
    title: l("Progetta una subnet", "Design a subnet", "Concevoir un sous-réseau", "Diseña una subred"),
    intro: l("Scegli prefisso, gateway e verifica la connettività di una piccola LAN.", "Choose the prefix and gateway, then verify a small LAN.", "Choisissez le préfixe et la passerelle, puis vérifiez le LAN.", "Elige el prefijo y la puerta de enlace, y verifica la LAN."),
    steps: [
      { task: l("Scegli la subnet più piccola per 50 host", "Choose the smallest subnet for 50 hosts", "Choisissez le plus petit sous-réseau pour 50 hôtes", "Elige la subred más pequeña para 50 hosts"), context: l("Rete disponibile: 192.168.10.0/24", "Available network: 192.168.10.0/24", "Réseau disponible : 192.168.10.0/24", "Red disponible: 192.168.10.0/24"), options: [l("/25 — 126 host", "/25 — 126 hosts", "/25 — 126 hôtes", "/25 — 126 hosts"), l("/26 — 62 host", "/26 — 62 hosts", "/26 — 62 hôtes", "/26 — 62 hosts"), l("/27 — 30 host", "/27 — 30 hosts", "/27 — 30 hôtes", "/27 — 30 hosts")], correct: 1, explanation: l("Una /26 offre 62 indirizzi host utilizzabili.", "A /26 provides 62 usable host addresses.", "Un /26 fournit 62 adresses hôtes utilisables.", "Una /26 proporciona 62 direcciones utilizables.") },
      { task: l("Configura il gateway della prima subnet", "Configure the first subnet gateway", "Configurez la passerelle du premier sous-réseau", "Configura la puerta de enlace de la primera subred"), context: l("Subnet: 192.168.10.0/26", "Subnet: 192.168.10.0/26", "Sous-réseau : 192.168.10.0/26", "Subred: 192.168.10.0/26"), options: [l("192.168.10.0", "192.168.10.0", "192.168.10.0", "192.168.10.0"), l("192.168.10.1", "192.168.10.1", "192.168.10.1", "192.168.10.1"), l("192.168.10.63", "192.168.10.63", "192.168.10.63", "192.168.10.63")], correct: 1, explanation: l(".0 è la rete e .63 il broadcast; .1 è un host valido.", ".0 is the network and .63 the broadcast; .1 is valid.", ".0 est le réseau et .63 le broadcast ; .1 est valide.", ".0 es la red y .63 el broadcast; .1 es válido.") },
      { task: l("Verifica il gateway dal client", "Verify the gateway from the client", "Vérifiez la passerelle depuis le client", "Verifica la puerta de enlace desde el cliente"), context: l("Terminale client Windows", "Windows client terminal", "Terminal client Windows", "Terminal de cliente Windows"), options: [l("ping 192.168.10.1", "ping 192.168.10.1", "ping 192.168.10.1", "ping 192.168.10.1"), l("nslookup /26", "nslookup /26", "nslookup /26", "nslookup /26"), l("route delete 0.0.0.0", "route delete 0.0.0.0", "route delete 0.0.0.0", "route delete 0.0.0.0")], correct: 0, explanation: l("ping verifica rapidamente la raggiungibilità IP.", "ping quickly verifies IP reachability.", "ping vérifie rapidement l'accessibilité IP.", "ping verifica rápidamente la conectividad IP.") },
    ],
  },
  "password-security": {
    eyebrow: "Security Lab", accent: "from-slate-950 to-rose-950", panel: "border-rose-200 bg-rose-50",
    title: l("Metti in sicurezza un account", "Secure an account", "Sécuriser un compte", "Protege una cuenta"), intro: l("Riduci il rischio di compromissione con scelte concrete.", "Reduce compromise risk with practical choices.", "Réduisez le risque de compromission avec des choix concrets.", "Reduce el riesgo de compromiso con decisiones concretas."),
    steps: [
      { task: l("Scegli la password più resistente", "Choose the strongest password", "Choisissez le mot de passe le plus robuste", "Elige la contraseña más resistente"), context: l("Account amministratore", "Administrator account", "Compte administrateur", "Cuenta de administrador"), options: [l("Estate2026!", "Summer2026!", "Ete2026!", "Verano2026!"), l("corretto-cactus-orbita-viola", "correct-horse-orbit-violet", "correct-cheval-orbite-violet", "correcto-caballo-orbita-violeta"), l("P@ssw0rd123", "P@ssw0rd123", "P@ssw0rd123", "P@ssw0rd123")], correct: 1, explanation: l("Una passphrase lunga e unica resiste meglio agli attacchi.", "A long, unique passphrase better resists attacks.", "Une phrase secrète longue et unique résiste mieux.", "Una frase larga y única resiste mejor los ataques.") },
      { task: l("Aggiungi un secondo fattore", "Add a second factor", "Ajoutez un second facteur", "Añade un segundo factor"), context: l("Sono disponibili tre metodi", "Three methods are available", "Trois méthodes sont disponibles", "Hay tres métodos disponibles"), options: [l("Domanda segreta", "Security question", "Question secrète", "Pregunta secreta"), l("Codice via email", "Email code", "Code par e-mail", "Código por correo"), l("Chiave di sicurezza FIDO2", "FIDO2 security key", "Clé de sécurité FIDO2", "Llave de seguridad FIDO2")], correct: 2, explanation: l("FIDO2 è resistente al phishing e non usa segreti condivisi.", "FIDO2 is phishing-resistant and uses no shared secrets.", "FIDO2 résiste au phishing et n'utilise aucun secret partagé.", "FIDO2 resiste al phishing y no usa secretos compartidos.") },
      { task: l("Gestisci le credenziali in modo sicuro", "Manage credentials safely", "Gérez les identifiants en sécurité", "Gestiona las credenciales de forma segura"), context: l("Hai decine di account diversi", "You have dozens of accounts", "Vous avez des dizaines de comptes", "Tienes decenas de cuentas"), options: [l("Riusa una password forte", "Reuse one strong password", "Réutiliser un mot de passe robuste", "Reutilizar una contraseña fuerte"), l("Usa un password manager", "Use a password manager", "Utiliser un gestionnaire de mots de passe", "Usar un gestor de contraseñas"), l("Salvale in un file di testo", "Save them in a text file", "Les enregistrer dans un fichier texte", "Guardarlas en un archivo de texto")], correct: 1, explanation: l("Il password manager genera e conserva password uniche.", "A password manager generates and stores unique passwords.", "Un gestionnaire génère et stocke des mots de passe uniques.", "Un gestor genera y guarda contraseñas únicas.") },
    ],
  },
  "linux-permissions": {
    eyebrow: "Linux Lab", accent: "from-slate-950 to-amber-900", panel: "border-amber-200 bg-amber-50",
    title: l("Ripara i permessi Linux", "Fix Linux permissions", "Réparer les permissions Linux", "Repara permisos Linux"), intro: l("Interpreta rwx e applica il minimo privilegio.", "Interpret rwx and apply least privilege.", "Interprétez rwx et appliquez le moindre privilège.", "Interpreta rwx y aplica mínimo privilegio."),
    steps: [
      { task: l("Leggi i permessi correnti", "Read current permissions", "Lisez les permissions actuelles", "Lee los permisos actuales"), context: l("-rw-r----- report.csv", "-rw-r----- report.csv", "-rw-r----- report.csv", "-rw-r----- report.csv"), options: [l("Owner: rw, gruppo: r, altri: nessuno", "Owner: rw, group: r, others: none", "Propriétaire : rw, groupe : r, autres : aucun", "Propietario: rw, grupo: r, otros: ninguno"), l("Tutti possono scrivere", "Everyone can write", "Tout le monde peut écrire", "Todos pueden escribir"), l("Solo il gruppo può eseguire", "Only the group can execute", "Seul le groupe peut exécuter", "Solo el grupo puede ejecutar")], correct: 0, explanation: l("Le tre triplette descrivono owner, group e others.", "The three triplets describe owner, group and others.", "Les trois triplets décrivent propriétaire, groupe et autres.", "Los tres tríos describen propietario, grupo y otros.") },
      { task: l("Imposta rw per owner e r per gruppo", "Set rw for owner and r for group", "Définissez rw pour le propriétaire et r pour le groupe", "Configura rw para propietario y r para grupo"), context: l("Nessun accesso agli altri utenti", "No access for other users", "Aucun accès pour les autres", "Sin acceso para otros usuarios"), options: [l("chmod 640 report.csv", "chmod 640 report.csv", "chmod 640 report.csv", "chmod 640 report.csv"), l("chmod 777 report.csv", "chmod 777 report.csv", "chmod 777 report.csv", "chmod 777 report.csv"), l("chmod 444 report.csv", "chmod 444 report.csv", "chmod 444 report.csv", "chmod 444 report.csv")], correct: 0, explanation: l("6=rw, 4=r e 0=nessun permesso.", "6=rw, 4=r and 0=no permissions.", "6=rw, 4=r et 0=aucune permission.", "6=rw, 4=r y 0=sin permisos.") },
      { task: l("Cambia il gruppo proprietario", "Change the owning group", "Changez le groupe propriétaire", "Cambia el grupo propietario"), context: l("Il gruppo corretto è finance", "The correct group is finance", "Le groupe correct est finance", "El grupo correcto es finance"), options: [l("chgrp finance report.csv", "chgrp finance report.csv", "chgrp finance report.csv", "chgrp finance report.csv"), l("grep finance report.csv", "grep finance report.csv", "grep finance report.csv", "grep finance report.csv"), l("passwd finance", "passwd finance", "passwd finance", "passwd finance")], correct: 0, explanation: l("chgrp modifica il gruppo proprietario di un file.", "chgrp changes a file's owning group.", "chgrp modifie le groupe propriétaire d'un fichier.", "chgrp cambia el grupo propietario de un archivo.") },
    ],
  },
  "sql-select": {
    eyebrow: "SQL Lab", accent: "from-violet-950 to-indigo-900", panel: "border-violet-200 bg-violet-50",
    title: l("Interroga il database vendite", "Query the sales database", "Interroger la base des ventes", "Consulta la base de ventas"), intro: l("Costruisci una query SELECT filtrata e ordinata.", "Build a filtered and sorted SELECT query.", "Construisez une requête SELECT filtrée et triée.", "Construye una consulta SELECT filtrada y ordenada."),
    steps: [
      { task: l("Seleziona nome e totale", "Select name and total", "Sélectionnez nom et total", "Selecciona nombre y total"), context: l("Tabella: orders", "Table: orders", "Table : orders", "Tabla: orders"), options: [l("SELECT name, total FROM orders;", "SELECT name, total FROM orders;", "SELECT name, total FROM orders;", "SELECT name, total FROM orders;"), l("GET name, total IN orders;", "GET name, total IN orders;", "GET name, total IN orders;", "GET name, total IN orders;"), l("SELECT orders INTO name;", "SELECT orders INTO name;", "SELECT orders INTO name;", "SELECT orders INTO name;")], correct: 0, explanation: l("SELECT elenca le colonne, FROM indica la tabella.", "SELECT lists columns and FROM identifies the table.", "SELECT liste les colonnes et FROM indique la table.", "SELECT lista columnas y FROM indica la tabla.") },
      { task: l("Mostra solo ordini sopra 100 €", "Show only orders over €100", "Affichez uniquement les commandes supérieures à 100 €", "Muestra solo pedidos superiores a 100 €"), context: l("Aggiungi una clausola alla query", "Add a clause to the query", "Ajoutez une clause à la requête", "Añade una cláusula a la consulta"), options: [l("WHERE total > 100", "WHERE total > 100", "WHERE total > 100", "WHERE total > 100"), l("HAVING orders > 100", "HAVING orders > 100", "HAVING orders > 100", "HAVING orders > 100"), l("LIMIT total = 100", "LIMIT total = 100", "LIMIT total = 100", "LIMIT total = 100")], correct: 0, explanation: l("WHERE filtra le righe prima di aggregazioni e ordinamento.", "WHERE filters rows before aggregation and sorting.", "WHERE filtre les lignes avant l'agrégation et le tri.", "WHERE filtra filas antes de agregar y ordenar.") },
      { task: l("Ordina dal totale più alto", "Sort by highest total", "Triez du total le plus élevé", "Ordena por total más alto"), context: l("Completa la query", "Complete the query", "Complétez la requête", "Completa la consulta"), options: [l("ORDER BY total DESC", "ORDER BY total DESC", "ORDER BY total DESC", "ORDER BY total DESC"), l("SORT total HIGH", "SORT total HIGH", "SORT total HIGH", "SORT total HIGH"), l("GROUP BY total ASC", "GROUP BY total ASC", "GROUP BY total ASC", "GROUP BY total ASC")], correct: 0, explanation: l("DESC ordina i valori in ordine decrescente.", "DESC sorts values in descending order.", "DESC trie les valeurs par ordre décroissant.", "DESC ordena los valores de forma descendente.") },
    ],
  },
  "docker-lifecycle": {
    eyebrow: "Docker Lab", accent: "from-sky-950 to-cyan-800", panel: "border-cyan-200 bg-cyan-50",
    title: l("Avvia un container web", "Launch a web container", "Lancer un conteneur web", "Inicia un contenedor web"), intro: l("Scarica, avvia e ispeziona un servizio Nginx.", "Pull, run and inspect an Nginx service.", "Téléchargez, lancez et inspectez un service Nginx.", "Descarga, inicia e inspecciona un servicio Nginx."),
    steps: [
      { task: l("Scarica l'immagine ufficiale", "Pull the official image", "Téléchargez l'image officielle", "Descarga la imagen oficial"), context: l("Immagine: nginx:alpine", "Image: nginx:alpine", "Image : nginx:alpine", "Imagen: nginx:alpine"), options: [l("docker pull nginx:alpine", "docker pull nginx:alpine", "docker pull nginx:alpine", "docker pull nginx:alpine"), l("docker get nginx:alpine", "docker get nginx:alpine", "docker get nginx:alpine", "docker get nginx:alpine"), l("docker build nginx:alpine", "docker build nginx:alpine", "docker build nginx:alpine", "docker build nginx:alpine")], correct: 0, explanation: l("docker pull scarica un'immagine dal registry.", "docker pull downloads an image from a registry.", "docker pull télécharge une image depuis un registre.", "docker pull descarga una imagen del registro.") },
      { task: l("Avvia il servizio sulla porta 8080", "Run the service on port 8080", "Lancez le service sur le port 8080", "Inicia el servicio en el puerto 8080"), context: l("Nginx ascolta sulla porta 80 nel container", "Nginx listens on port 80 in the container", "Nginx écoute sur le port 80 du conteneur", "Nginx escucha en el puerto 80 del contenedor"), options: [l("docker run -d -p 8080:80 nginx:alpine", "docker run -d -p 8080:80 nginx:alpine", "docker run -d -p 8080:80 nginx:alpine", "docker run -d -p 8080:80 nginx:alpine"), l("docker run -p 80:8080 nginx:alpine", "docker run -p 80:8080 nginx:alpine", "docker run -p 80:8080 nginx:alpine", "docker run -p 80:8080 nginx:alpine"), l("docker start 8080 nginx", "docker start 8080 nginx", "docker start 8080 nginx", "docker start 8080 nginx")], correct: 0, explanation: l("La sintassi del mapping è porta-host:porta-container.", "Port mapping uses host-port:container-port.", "Le mapping utilise port-hôte:port-conteneur.", "El mapeo usa puerto-host:puerto-contenedor.") },
      { task: l("Controlla i container attivi", "Check running containers", "Vérifiez les conteneurs actifs", "Comprueba los contenedores activos"), context: l("Verifica stato e porte", "Verify status and ports", "Vérifiez l'état et les ports", "Verifica estado y puertos"), options: [l("docker ps", "docker ps", "docker ps", "docker ps"), l("docker images", "docker images", "docker images", "docker images"), l("docker init", "docker init", "docker init", "docker init")], correct: 0, explanation: l("docker ps elenca i container attualmente in esecuzione.", "docker ps lists currently running containers.", "docker ps liste les conteneurs en cours d'exécution.", "docker ps lista los contenedores en ejecución.") },
    ],
  },
  "cloud-storage-security": {
    eyebrow: "Cloud Security Lab", accent: "from-blue-950 to-indigo-800", panel: "border-blue-200 bg-blue-50",
    title: l("Proteggi un archivio cloud", "Secure cloud storage", "Sécuriser un stockage cloud", "Protege un almacenamiento cloud"), intro: l("Metti in sicurezza un bucket che contiene documenti aziendali.", "Secure a bucket containing company documents.", "Sécurisez un bucket contenant des documents d'entreprise.", "Protege un bucket que contiene documentos de la empresa."),
    steps: [
      { task: l("Blocca l'esposizione su Internet", "Block Internet exposure", "Bloquez l'exposition sur Internet", "Bloquea la exposición en Internet"), context: l("Il bucket consente lettura pubblica anonima", "The bucket allows anonymous public reads", "Le bucket autorise la lecture publique anonyme", "El bucket permite lectura pública anónima"), options: [l("Abilita Block Public Access", "Enable Block Public Access", "Activer le blocage de l'accès public", "Activar el bloqueo de acceso público"), l("Rinomina il bucket", "Rename the bucket", "Renommer le bucket", "Cambiar el nombre del bucket"), l("Aumenta la capacità", "Increase capacity", "Augmenter la capacité", "Aumentar la capacidad")], correct: 0, explanation: l("Il blocco dell'accesso pubblico rimuove l'esposizione anonima.", "Blocking public access removes anonymous exposure.", "Le blocage de l'accès public supprime l'exposition anonyme.", "Bloquear el acceso público elimina la exposición anónima.") },
      { task: l("Concedi accesso all'applicazione", "Grant application access", "Accordez l'accès à l'application", "Concede acceso a la aplicación"), context: l("L'app deve soltanto leggere la cartella reports/", "The app only needs to read the reports/ folder", "L'application doit seulement lire le dossier reports/", "La aplicación solo debe leer la carpeta reports/"), options: [l("Ruolo con lettura limitata a reports/", "Role with read access limited to reports/", "Rôle avec lecture limitée à reports/", "Rol con lectura limitada a reports/"), l("Credenziali amministratore", "Administrator credentials", "Identifiants administrateur", "Credenciales de administrador"), l("Accesso completo a tutti i bucket", "Full access to every bucket", "Accès complet à tous les buckets", "Acceso completo a todos los buckets")], correct: 0, explanation: l("Un ruolo ristretto applica il principio del minimo privilegio.", "A restricted role applies least privilege.", "Un rôle restreint applique le moindre privilège.", "Un rol restringido aplica mínimo privilegio.") },
      { task: l("Proteggi i file archiviati", "Protect stored files", "Protégez les fichiers stockés", "Protege los archivos almacenados"), context: l("I documenti contengono dati riservati", "Documents contain confidential data", "Les documents contiennent des données confidentielles", "Los documentos contienen datos confidenciales"), options: [l("Abilita cifratura e versioning", "Enable encryption and versioning", "Activer le chiffrement et le versioning", "Activar cifrado y versionado"), l("Disabilita i log", "Disable logs", "Désactiver les journaux", "Desactivar los registros"), l("Comprimi i file", "Compress the files", "Compresser les fichiers", "Comprimir los archivos")], correct: 0, explanation: l("Cifratura e versioning proteggono riservatezza e recupero.", "Encryption and versioning protect confidentiality and recovery.", "Le chiffrement et le versioning protègent confidentialité et récupération.", "El cifrado y versionado protegen confidencialidad y recuperación.") },
    ],
  },
  "ai-prompt-safety": {
    eyebrow: "Responsible AI Lab", accent: "from-fuchsia-950 to-violet-800", panel: "border-fuchsia-200 bg-fuchsia-50",
    title: l("Progetta un prompt AI sicuro", "Design a safe AI prompt", "Concevoir un prompt IA sûr", "Diseña un prompt de IA seguro"), intro: l("Usa un assistente AI senza esporre dati o accettare risposte non verificate.", "Use an AI assistant without exposing data or accepting unverified answers.", "Utilisez un assistant IA sans exposer de données ni accepter de réponses non vérifiées.", "Usa un asistente de IA sin exponer datos ni aceptar respuestas no verificadas."),
    steps: [
      { task: l("Prepara i dati da inviare", "Prepare data to send", "Préparez les données à envoyer", "Prepara los datos que enviarás"), context: l("Il testo contiene nome, email e numero cliente", "The text contains a name, email and customer number", "Le texte contient nom, e-mail et numéro client", "El texto contiene nombre, correo y número de cliente"), options: [l("Anonimizza i dati personali", "Anonymize personal data", "Anonymiser les données personnelles", "Anonimizar los datos personales"), l("Invia tutto per avere più contesto", "Send everything for more context", "Tout envoyer pour plus de contexte", "Enviar todo para dar más contexto"), l("Aggiungi la password del cliente", "Add the customer's password", "Ajouter le mot de passe du client", "Añadir la contraseña del cliente")], correct: 0, explanation: l("La minimizzazione dei dati riduce il rischio di esposizione.", "Data minimization reduces exposure risk.", "La minimisation des données réduit le risque d'exposition.", "La minimización de datos reduce el riesgo de exposición.") },
      { task: l("Riduci risposte inventate", "Reduce fabricated answers", "Réduisez les réponses inventées", "Reduce respuestas inventadas"), context: l("Serve un riepilogo basato solo sul documento", "A summary must use only the document", "Le résumé doit utiliser uniquement le document", "El resumen debe usar solo el documento"), options: [l("Chiedi citazioni e di dichiarare informazioni mancanti", "Request citations and disclosure of missing information", "Demander des citations et de signaler les informations manquantes", "Pedir citas e indicar la información ausente"), l("Chiedi di essere creativo", "Ask it to be creative", "Demander d'être créatif", "Pedir que sea creativo"), l("Elimina il documento", "Remove the document", "Supprimer le document", "Eliminar el documento")], correct: 0, explanation: l("Vincoli e riferimenti rendono la risposta più verificabile.", "Constraints and references make the answer more verifiable.", "Les contraintes et références rendent la réponse plus vérifiable.", "Las restricciones y referencias hacen la respuesta más verificable.") },
      { task: l("Usa il risultato in una decisione", "Use the result in a decision", "Utilisez le résultat dans une décision", "Usa el resultado en una decisión"), context: l("L'AI suggerisce di rifiutare una candidatura", "The AI suggests rejecting an applicant", "L'IA suggère de rejeter une candidature", "La IA sugiere rechazar una candidatura"), options: [l("Verifica fonti e mantieni revisione umana", "Verify sources and keep human review", "Vérifier les sources et maintenir un contrôle humain", "Verificar fuentes y mantener revisión humana"), l("Applica automaticamente la decisione", "Apply the decision automatically", "Appliquer automatiquement la décision", "Aplicar automáticamente la decisión"), l("Nascondi l'uso dell'AI", "Hide the use of AI", "Cacher l'utilisation de l'IA", "Ocultar el uso de IA")], correct: 0, explanation: l("Le decisioni ad alto impatto richiedono controllo umano e verifiche.", "High-impact decisions require human oversight and verification.", "Les décisions à fort impact exigent contrôle humain et vérification.", "Las decisiones de alto impacto requieren supervisión humana y verificación.") },
    ],
  },
  "python-data-cleanup": {
    eyebrow: "Python Lab", accent: "from-slate-950 to-yellow-700", panel: "border-yellow-200 bg-yellow-50",
    title: l("Pulisci dati con Python", "Clean data with Python", "Nettoyer des données avec Python", "Limpia datos con Python"), intro: l("Correggi un piccolo dataset prima di calcolare le vendite medie.", "Fix a small dataset before calculating average sales.", "Corrigez un petit jeu de données avant de calculer les ventes moyennes.", "Corrige un pequeño conjunto de datos antes de calcular las ventas medias."),
    steps: [
      { task: l("Trova i valori mancanti", "Find missing values", "Trouvez les valeurs manquantes", "Encuentra los valores ausentes"), context: l("DataFrame pandas: sales", "pandas DataFrame: sales", "DataFrame pandas : sales", "DataFrame de pandas: sales"), options: [l("sales.isna().sum()", "sales.isna().sum()", "sales.isna().sum()", "sales.isna().sum()"), l("sales.print(null)", "sales.print(null)", "sales.print(null)", "sales.print(null)"), l("missing(sales)", "missing(sales)", "missing(sales)", "missing(sales)")], correct: 0, explanation: l("isna identifica i valori mancanti e sum li conta per colonna.", "isna identifies missing values and sum counts them by column.", "isna identifie les valeurs manquantes et sum les compte par colonne.", "isna identifica valores ausentes y sum los cuenta por columna.") },
      { task: l("Rimuovi righe senza importo", "Remove rows without an amount", "Supprimez les lignes sans montant", "Elimina filas sin importe"), context: l("La colonna obbligatoria è amount", "The required column is amount", "La colonne obligatoire est amount", "La columna obligatoria es amount"), options: [l("sales.dropna(subset=['amount'])", "sales.dropna(subset=['amount'])", "sales.dropna(subset=['amount'])", "sales.dropna(subset=['amount'])"), l("sales.drop('amount')", "sales.drop('amount')", "sales.drop('amount')", "sales.drop('amount')"), l("sales.fillna('amount')", "sales.fillna('amount')", "sales.fillna('amount')", "sales.fillna('amount')")], correct: 0, explanation: l("dropna con subset elimina solo le righe prive del campo richiesto.", "dropna with subset removes only rows missing the required field.", "dropna avec subset supprime seulement les lignes sans champ requis.", "dropna con subset elimina solo filas sin el campo requerido.") },
      { task: l("Calcola la media affidabile", "Calculate the reliable average", "Calculez la moyenne fiable", "Calcula la media fiable"), context: l("Il DataFrame pulito si chiama clean_sales", "The cleaned DataFrame is clean_sales", "Le DataFrame nettoyé est clean_sales", "El DataFrame limpio es clean_sales"), options: [l("clean_sales['amount'].mean()", "clean_sales['amount'].mean()", "clean_sales['amount'].mean()", "clean_sales['amount'].mean()"), l("mean.clean_sales.amount", "mean.clean_sales.amount", "mean.clean_sales.amount", "mean.clean_sales.amount"), l("clean_sales.count('average')", "clean_sales.count('average')", "clean_sales.count('average')", "clean_sales.count('average')")], correct: 0, explanation: l("mean calcola la media numerica della serie selezionata.", "mean calculates the numeric average of the selected Series.", "mean calcule la moyenne numérique de la série sélectionnée.", "mean calcula la media numérica de la serie seleccionada.") },
    ],
  },
  "windows-server-users": {
    eyebrow: "Windows Server Lab", accent: "from-slate-950 to-blue-900", panel: "border-slate-300 bg-slate-50",
    title: l("Gestisci utenti di dominio", "Manage domain users", "Gérer les utilisateurs du domaine", "Gestiona usuarios del dominio"), intro: l("Configura un nuovo dipendente in Active Directory con accessi appropriati.", "Configure a new employee in Active Directory with appropriate access.", "Configurez un nouvel employé dans Active Directory avec les accès appropriés.", "Configura un nuevo empleado en Active Directory con los accesos adecuados."),
    steps: [
      { task: l("Crea l'account nella posizione corretta", "Create the account in the correct location", "Créez le compte au bon emplacement", "Crea la cuenta en la ubicación correcta"), context: l("Utente: Sara Bianchi, reparto Finance", "User: Sara Bianchi, Finance department", "Utilisateur : Sara Bianchi, service Finance", "Usuario: Sara Bianchi, departamento Finance"), options: [l("Crea l'utente nella OU Finance", "Create the user in the Finance OU", "Créer l'utilisateur dans l'OU Finance", "Crear el usuario en la OU Finance"), l("Usa il contenitore Computers", "Use the Computers container", "Utiliser le conteneur Computers", "Usar el contenedor Computers"), l("Crea un amministratore di dominio", "Create a domain administrator", "Créer un administrateur du domaine", "Crear un administrador del dominio")], correct: 0, explanation: l("La OU corretta consente di applicare deleghe e policy del reparto.", "The correct OU enables department delegation and policies.", "La bonne OU permet les délégations et stratégies du service.", "La OU correcta permite delegaciones y políticas del departamento.") },
      { task: l("Assegna l'accesso ai file", "Assign file access", "Attribuez l'accès aux fichiers", "Asigna acceso a los archivos"), context: l("Il gruppo Finance-Read dispone già dei permessi necessari", "Finance-Read already has the required permissions", "Finance-Read possède déjà les permissions requises", "Finance-Read ya tiene los permisos necesarios"), options: [l("Aggiungi Sara a Finance-Read", "Add Sara to Finance-Read", "Ajouter Sara à Finance-Read", "Añadir a Sara a Finance-Read"), l("Concedi Full Control direttamente", "Grant Full Control directly", "Accorder directement le contrôle total", "Conceder Control total directamente"), l("Aggiungila a Domain Admins", "Add her to Domain Admins", "L'ajouter à Domain Admins", "Añadirla a Domain Admins")], correct: 0, explanation: l("I permessi tramite gruppi sono più sicuri e gestibili.", "Group-based permissions are safer and easier to manage.", "Les permissions par groupe sont plus sûres et faciles à gérer.", "Los permisos por grupos son más seguros y fáciles de gestionar.") },
      { task: l("Imposta il primo accesso", "Configure first sign-in", "Configurez la première connexion", "Configura el primer inicio"), context: l("È stata generata una password temporanea", "A temporary password was generated", "Un mot de passe temporaire a été généré", "Se generó una contraseña temporal"), options: [l("Richiedi cambio password al prossimo accesso", "Require password change at next sign-in", "Exiger le changement du mot de passe à la prochaine connexion", "Exigir cambio de contraseña en el próximo inicio"), l("Imposta password senza scadenza", "Set password to never expire", "Définir un mot de passe sans expiration", "Establecer contraseña sin caducidad"), l("Invia la password in un canale pubblico", "Send the password in a public channel", "Envoyer le mot de passe dans un canal public", "Enviar la contraseña por un canal público")], correct: 0, explanation: l("Il cambio al primo accesso impedisce di conservare la password temporanea.", "Changing it at first sign-in prevents retention of the temporary password.", "Le changement à la première connexion évite de conserver le mot de passe temporaire.", "El cambio en el primer inicio evita conservar la contraseña temporal.") },
    ],
  },
  "powershell-pipeline": {
    eyebrow: "PowerShell Lab", accent: "from-blue-950 to-indigo-900", panel: "border-blue-200 bg-blue-50",
    title: l("Costruisci una pipeline", "Build a pipeline", "Construire un pipeline", "Construye una pipeline"), intro: l("Filtra processi, seleziona proprietà ed esporta i risultati.", "Filter processes, select properties and export results.", "Filtrez les processus, sélectionnez les propriétés et exportez.", "Filtra procesos, selecciona propiedades y exporta."),
    steps: [
      { task: l("Ottieni i processi in esecuzione", "Get running processes", "Obtenez les processus en cours", "Obtén los procesos en ejecución"), context: l("Console PowerShell", "PowerShell console", "Console PowerShell", "Consola PowerShell"), options: [l("Get-Process", "Get-Process", "Get-Process", "Get-Process"), l("List-Process", "List-Process", "List-Process", "List-Process"), l("Open-Process", "Open-Process", "Open-Process", "Open-Process")], correct: 0, explanation: l("Get-Process restituisce oggetti processo, non semplice testo.", "Get-Process returns process objects, not plain text.", "Get-Process renvoie des objets processus, pas du texte simple.", "Get-Process devuelve objetos de proceso, no texto simple.") },
      { task: l("Filtra quelli che usano oltre 100 MB", "Filter those using over 100 MB", "Filtrez ceux utilisant plus de 100 Mo", "Filtra los que usan más de 100 MB"), context: l("Continua dopo Get-Process |", "Continue after Get-Process |", "Continuez après Get-Process |", "Continúa después de Get-Process |"), options: [l("Where-Object WorkingSet64 -gt 100MB", "Where-Object WorkingSet64 -gt 100MB", "Where-Object WorkingSet64 -gt 100MB", "Where-Object WorkingSet64 -gt 100MB"), l("Find Memory > 100", "Find Memory > 100", "Find Memory > 100", "Find Memory > 100"), l("Select-Object 100MB", "Select-Object 100MB", "Select-Object 100MB", "Select-Object 100MB")], correct: 0, explanation: l("Where-Object filtra gli oggetti usando le loro proprietà.", "Where-Object filters objects using their properties.", "Where-Object filtre les objets via leurs propriétés.", "Where-Object filtra objetos mediante sus propiedades.") },
      { task: l("Esporta nome e memoria in CSV", "Export name and memory to CSV", "Exportez nom et mémoire en CSV", "Exporta nombre y memoria a CSV"), context: l("Completa la pipeline", "Complete the pipeline", "Complétez le pipeline", "Completa la pipeline"), options: [l("Select Name, WorkingSet64 | Export-Csv processes.csv", "Select Name, WorkingSet64 | Export-Csv processes.csv", "Select Name, WorkingSet64 | Export-Csv processes.csv", "Select Name, WorkingSet64 | Export-Csv processes.csv"), l("Write-Host processes.csv", "Write-Host processes.csv", "Write-Host processes.csv", "Write-Host processes.csv"), l("ConvertTo-Html processes.csv", "ConvertTo-Html processes.csv", "ConvertTo-Html processes.csv", "ConvertTo-Html processes.csv")], correct: 0, explanation: l("Select sceglie le proprietà ed Export-Csv serializza gli oggetti.", "Select chooses properties and Export-Csv serializes objects.", "Select choisit les propriétés et Export-Csv sérialise les objets.", "Select elige propiedades y Export-Csv serializa los objetos.") },
    ],
  },
};

const ui = {
  it: { score: "Punteggio", step: "Obiettivo", choose: "Scegli l'azione corretta", correct: "Corretto!", wrong: "Non è la scelta giusta. Riprova.", hint: "Mostra suggerimento", next: "Prossimo obiettivo", done: "Laboratorio completato", doneBody: "Hai portato a termine tutte le attività.", reset: "Ricomincia" },
  en: { score: "Score", step: "Objective", choose: "Choose the correct action", correct: "Correct!", wrong: "That is not the right choice. Try again.", hint: "Show hint", next: "Next objective", done: "Lab completed", doneBody: "You completed every task.", reset: "Restart" },
  fr: { score: "Score", step: "Objectif", choose: "Choisissez l'action correcte", correct: "Correct !", wrong: "Ce n'est pas le bon choix. Réessayez.", hint: "Afficher l'indice", next: "Objectif suivant", done: "Lab terminé", doneBody: "Vous avez terminé toutes les tâches.", reset: "Recommencer" },
  es: { score: "Puntuación", step: "Objetivo", choose: "Elige la acción correcta", correct: "¡Correcto!", wrong: "No es la opción correcta. Inténtalo de nuevo.", hint: "Mostrar pista", next: "Siguiente objetivo", done: "Lab completado", doneBody: "Has completado todas las tareas.", reset: "Reiniciar" },
} as const;

export default function ScenarioChallengeLab({ lang, slug, onComplete }: { lang: Locale; slug: LabSlug; onComplete: () => void }) {
  const challenge = scenarioChallenges[slug];
  const t = ui[lang];
  const [step, setStep] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [score, setScore] = useState(100);
  const [message, setMessage] = useState("");
  const [showHint, setShowHint] = useState(false);
  if (!challenge) return null;
  const current = challenge.steps[step];
  const done = step >= challenge.steps.length;
  const verify = (index: number) => {
    if (!current) return;
    setSelected(index);
    if (index === current.correct) setMessage(t.correct);
    else { setMessage(t.wrong); setScore(value => Math.max(0, value - 10)); }
  };
  const next = () => {
    if (!current || selected !== current.correct) return;
    if (step === challenge.steps.length - 1) { setStep(challenge.steps.length); onComplete(); }
    else setStep(value => value + 1);
    setSelected(null); setMessage(""); setShowHint(false);
  };
  const reset = () => { setStep(0); setSelected(null); setScore(100); setMessage(""); setShowHint(false); };
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl">
    <header className={`bg-gradient-to-r ${challenge.accent} p-5 text-white sm:p-7`}><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-white/70"><Terminal size={16} />{challenge.eyebrow}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-black sm:text-3xl">{challenge.title[lang]}</h1><span className="rounded-full bg-white/10 px-3 py-1 text-sm font-bold">{t.score}: {score}</span></div><p className="mt-3 max-w-3xl text-white/80">{challenge.intro[lang]}</p></header>
    <div className="grid md:grid-cols-[240px_1fr]"><aside className="border-b bg-slate-50 p-5 md:border-b-0 md:border-r"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{t.step}</p><div className="mt-4 space-y-3">{challenge.steps.map((item, index) => <div key={item.task.en} className={`flex gap-2 text-sm ${index < step ? "font-semibold text-emerald-700" : index === step ? "font-bold text-slate-950" : "text-slate-400"}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full text-xs ${index < step ? "bg-emerald-100" : index === step ? "bg-indigo-100 text-indigo-700" : "bg-slate-200"}`}>{index < step ? <CheckCircle2 size={15} /> : index + 1}</span><span>{item.task[lang]}</span></div>)}</div></aside>
      <section className="p-4 sm:p-7">{done ? <div className="py-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={52} /><h2 className="mt-4 text-2xl font-black">{t.done}</h2><p className="mt-2 text-slate-600">{t.doneBody}</p><p className="mt-4 text-lg font-bold text-indigo-700">{t.score}: {score}/100</p><button onClick={reset} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-5 font-bold hover:bg-slate-50"><RotateCcw size={17} />{t.reset}</button></div> : <><div className={`rounded-xl border p-4 ${challenge.panel}`}><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{t.step} {step + 1}/{challenge.steps.length}</p><h2 className="mt-1 text-xl font-black">{current.task[lang]}</h2><p className="mt-2 font-mono text-sm text-slate-700">{current.context[lang]}</p></div><h3 className="mt-5 font-bold">{t.choose}</h3><div className="mt-3 grid gap-3">{current.options.map((option, index) => <button key={option.en} onClick={() => verify(index)} className={`min-h-12 rounded-xl border p-3 text-left font-mono text-sm transition ${selected === index ? index === current.correct ? "border-emerald-500 bg-emerald-50 text-emerald-900" : "border-rose-400 bg-rose-50 text-rose-900" : "border-slate-200 hover:border-indigo-400 hover:bg-indigo-50"}`}>{option[lang]}</button>)}</div>{message && <div className={`mt-4 rounded-xl p-3 text-sm ${selected === current.correct ? "bg-emerald-100 text-emerald-900" : "bg-rose-100 text-rose-900"}`}><strong>{message}</strong>{selected === current.correct && <p className="mt-1">{current.explanation[lang]}</p>}</div>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={() => { if (!showHint) setScore(value => Math.max(0, value - 5)); setShowHint(true); }} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 text-sm font-bold text-amber-800"><Lightbulb size={16} />{t.hint} (-5)</button>{selected === current.correct && <button onClick={next} className="min-h-11 rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white hover:bg-indigo-700">{step === challenge.steps.length - 1 ? t.done : t.next} →</button>}</div>{showHint && <p className="mt-3 text-sm text-amber-800">{current.explanation[lang]}</p>}</>}</section>
    </div>
  </div>;
}
